### ISSUE TITLE
ISSUE_CE_008: 2014-11-24 CE County - Stantec Stormwater Recommended site conflict with LUCHANGE proposed relocation sites.

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#10]
**WHAT** - There are 10 planned stormwater sites in CECIL county that are "recommended for restoration" after a field

**CONFLICT** -  LUCHANGE_BMP sites that are proposed potential relocation sites

**ACTION NEEDED** -  Stormwater teams must rework sites that are overlapping, and be aware of sites that are within 15 feet of existing plantings.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_CE-008

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Consultant has been informed of need to reshape potential BMPs:
Fri 12/5/2014 3:18 PM
Susan Foster SFoster@nmpengineering.com
Cecil County Gr1-Stantec Potential BMP Conflicts with Tree Planting Areas: Issue_CE_008
To: 'Haptemariam, Alex' alex.haptemariam@stantec.com; Postell, Rand rand.postell@stantec.com
Cc: Kristin Langway klangway@nmpengineering.com
Alex and Rand,

Good afternoon! I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants of conflicts so that they are able to reshape their potential BMP footprints to accommodate the tree site so as to avoid a conflict, and to be aware of nearby tree planting areas. These conflicting sites are tracked as “Issues,” and I am passing them along to the consultants for resolution. It is important to note that none of these potential BMP sites have gone to the concept design phase. A group of ten potential BMP sites identified through your desktop evaluation either conflict with tree planting areas or are located within close proximity to tree planting areas. Since these BMP sites are either within or nearby existing tree planting contracts, the potential BMP footprints must be reshaped by the consultant in order to avoid a conflict with the tree planting area footprint.  If a potential BMP site cannot be reshaped to accommodate the tree site, then the BMP site must be reclassified as future consideration. The reshaped BMP sites (or BMP sites that are unable to be reshaped, but have been moved to future consideration) must then be submitted through ProjectWise in order to update the database. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for  viewing/evaluating the possible reshaping of the BMP. The GIS potential BMP footprint and tree shapes are included in the feature classes (link below) for evaluation. 

Procedure:
1.  Download GIS file from ProjectWise: 2014-12-04_Ba_Co_Gr1-Stantec_Tree_ISSUE_CE_008.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Cecil\Gr1-STN\07-GIS\2014-12-04_Ba_Co_Gr1-Stantec_Tree_ISSUE_CE_008.gdb.zip)
2.  Open ArcMap and add GIS data to view the following feature classes:
   a.  LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.  ISSUE_CE_008:  A group of potential BMP sites that are in conflict – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
i.   

c.  TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.  Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the overlapping tree site boundary, and different green hatches to differentiate between the two tree areas per my preference for the example).
2.  Zoom to each EFF_BMP_PLANNED_ID within the Issue.
3.  Evaluate nature of conflict – below is an example of a conflict with graphic shown:
   a.  EFF_BMP_PLANNED_ID: 1eaa3f20-7ecd-46b8-8bf6-3a0a63ec9cf5
   NATURE OF CONFLICT (consultant to evaluate): Potential BMP site (in red outline) overlaps with tree site in LUCHANGE_BMP (tree site that is within a contract – densely hatched green and white area with green outline labeled with SITE_NAME 0700047AUT). Although this is also overlapping with TREE_SITE_SELECTION ( less densely hatched green and white area - not currently under contract because these are possible tree planting areas), the potential BMP footprint must be reshaped to accommodate the shape of LUCHANGE_BMP (because this is under contract). Please reshape potential BMP site if possible. If not possible, then move this potential BMP site to future consideration and make appropriate updates in GIS. Please keep in mind any clearances that potential BMPs may need in relation to the tree site before finalizing the revised footprint. It is advised to maintain a 20’ minimum clearance to the tree site footprint. If there is no overlap of a potential BMP with a tree planting area, please be aware of the nearby tree planting area for future reference.
4.  Determine a resolution: If the potential BMP footprint can be reshaped, the consultant must revise the shape in GIS. Again, if the potential BMP site is NOT able to be reshaped to accommodate the tree site, then it must be reclassified as future consideration within GIS. All changes must be posted on ProjectWise. Please email me when the changes have been posted, and also cc Kristin Langway (KLangway@sha.state.md.us).

Please let me know if you have any questions. Thank you for your work in helping us avoid tree conflicts! Have a great weekend!

Thanks,

Susie

**Comment by SRF-NMP** [comment]
Reminded consultant to acknowledge receipt of email sent 2014/12/05 and provide estimated day of competion (included original email, but did not repost in this comment):
Wed 12/17/2014 10:04 AM
Susan Foster SFoster@nmpengineering.com
Cecil County Gr1-Stantec Potential BMP Conflicts with Tree Planting Areas: Issue_CE_008
To: 'Haptemariam, Alex' alex.haptemariam@stantec.com; Postell, Rand rand.postell@stantec.com
Hi Alex and Rand,

I just wanted to check in and make sure you received my email below from December 5 and find out when you will be able to submit the revisions.  Please let me know as soon as possible so that I can schedule the GIS team. 

Thanks and have a good day!

Susie

**Comment by SRF-NMP** [comment]
Email below is a clarification to consultant: Issue is a group of sites - not one site:

From: Susan Foster 
Sent: Wednesday, December 17, 2014 3:37 PM
To: 'Haptemariam, Alex'; Postell, Rand; Negussie, Neftalem
Subject: RE: Cecil County Gr1-Stantec Potential BMP Conflicts with Tree Planting Areas: Issue_CE_008

Alex,

Thanks for your reply. Just to clarify, the subject is not an individual site. The tree “Issue” is a group of sites (in this case, ten, as described in the original email below and can be viewed through the link below, which you will need in order to review the conflicts). This group contains individual sites (as identified in Step 2 of the Procedure below). Please let me know if you have any questions! 

Thanks, 

Susie

From: Haptemariam, Alex [mailto:alex.haptemariam@stantec.com] 
Sent: Wednesday, December 17, 2014 11:58 AM
To: Susan Foster; Postell, Rand; Negussie, Neftalem
Subject: RE: Cecil County Gr1-Stantec Potential BMP Conflicts with Tree Planting Areas: Issue_CE_008

Susan,
There is no conflict in our site. The databases for site footprint are already on projectwise . Please let me know so Neftalem can direct you to the location of the updated GIS file so if you are not able to access it. 

Alex Haptemariam
Senior Project Manager
Stantec
6110 Frost Place Laurel MD 20707-2927
Phone: (301) 982-2895
Cell: (240) 432-9905
Fax: (301) 220-2595
alex.haptemariam@stantec.com

**Comment by SRF-NMP** [comment]
Per phone conversation 2014/12/18 with Alex and Neftalem, they now see conflict (that these are not the CD sites that were recently submitted) and will revise accordingly.

**Comment by SRF-NMP** [comment]
Followed up with consultant (Neftalem and Alex) and received autoreply that Neftalem will be out of office until Jan. 24.Alex was copied. Awaiting reply.

From: Negussie, Neftalem [mailto:neftalem.negussie@stantec.com] 
Sent: Tuesday, January 13, 2015 12:04 PM
To: Susan Foster
Subject: Out of Office: Updated GIS

I will be on vacation from December 22, 2014 to January 24, 2015. I may not have e-mail access during this period. For any concerns relating to SHA, please contact Alex Haptemariam at alex.haptemariam@stantec.com. Other questions please direct them to Kevin Donnelly at kevin.donnelly@stantec.com.

Thank you, 

Neftalem

From: Susan Foster 
Sent: Tuesday, January 13, 2015 12:03 PM
To: 'Negussie, Neftalem'
Cc: 'Haptemariam, Alex'
Subject: RE: Updated GIS

Neftalem,

Good afternoon! I am following up from our phone conversation 2014/12/18 with you and Alex – have you been able to reshape the sites?  

Thanks,
Susie

**Comment by SRF-NMP** [comment]
Since Neftalem is out of the office, Maribeth is taking this over. She thought they were concept design sites, and I reforwarded the original email with the database location/instructions for viewing/reshaping/reclassifying. I mentioned Neftalem was involved with the conversation and is aware that these are not concept sites. Email below.

From: Susan Foster 
Sent: Tuesday, January 13, 2015 4:47 PM
To: 'Armenio, Maribeth'
Cc: 'Haptemariam, Alex'
Subject: RE: Updated GIS

Maribeth,

Thanks you for your email – as discussed with  Alex and Neftalem and noted in the original email, these are not concept design sites. Alex was involved in the conversation with Neftalem when the sites were discussed. I am attaching the original email with instructions on viewing these and how to proceed with revisions. Please let me know if you are unable to access the data. If you could post the revised sites/statuses on PW as directed in the original email, that’d be great. 

Thank you very much, and have a good evening!

Susie

From: Armenio, Maribeth [mailto:Maribeth.Armenio@stantec.com] 
Sent: Tuesday, January 13, 2015 4:39 PM
To: Susan Foster
Cc: Haptemariam, Alex
Subject: FW: Updated GIS

Hi Susie,

Neftalem is out of the office for a couple more weeks so I will take a swing at your question but let me know if you need other information. I believe the only site we did a concept design for that was also effected by a future tree planting site on our near our BMP footprint is CE-027 . We did modify the footprint of the site to allow an ~8’ buffer between the tie in locations and tree location extent and meet ESDv requirements. If this does not appear to be addressed in the GIS files that were submitted to Projectwise, let me know. 

Thanks!
Maribeth Armenio
Engineering Project Specialist
Stantec
6110 Frost Place Laurel MD 20707-2927
Phone: (240) 542 - 3085
Maribeth.Armenio@stantec.com

**Comment by SRF-NMP** [comment]
Alex will address.  Email below.

From: Susan Foster 
Sent: Tuesday, January 13, 2015 4:53 PM
To: 'Haptemariam, Alex'
Subject: RE: Updated GIS

Thanks, Alex! I know things were very busy with the holidays, so no worries! Have a good evening!

From: Haptemariam, Alex [mailto:alex.haptemariam@stantec.com] 
Sent: Tuesday, January 13, 2015 4:52 PM
To: Susan Foster
Subject: RE: Updated GIS

Susan,
My apologies. I thought this has been taken care of by Neftalem at the time we had the discussions. We will take care of it. Thanks-

Alex Haptemariam
Senior Project Manager(Associate)
Stantec
6110 Frost Place Laurel MD 20707-2927
Phone: (301) 982-2895
Cell: (240) 432-9905
Fax: (301) 220-2595
alex.haptemariam@stantec.com

**Comment by SRF-NMP** [comment]
Consultant returned file, but nothing reshaped or reclassified. Asked for clarification/resubmitting shapes:
Maribeth,

I’m unable to find a file with the 10 reshaped sites/new statuses. The only file here has 188 shapes and nothing has changed. Is this the correct file?

Thanks,

Susie

From: Armenio, Maribeth [mailto:Maribeth.Armenio@stantec.com] 
Sent: Friday, January 16, 2015 8:31 AM
To: Susan Foster
Subject: RE: Updated GIS

Hi Susie,

Okay,  I uploaded that same database as a zip file in the location you have shown below. Hope this works! This is the path:

Pw:\shavmpwx.shacadd..ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation and Monitoring\SWM\New BMPs\Cecil\Gr1-STN\08 Submissions\2015-01-15-CE Co-STN-Submission#2

Maribeth Armenio

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Thursday, January 15, 2015 5:06 PM
To: Armenio, Maribeth
Subject: RE: Updated GIS

Maribeth,

I’m unable to open the files. These are the files I’m looking at below – is this the correct path? Would it be possible to post a zipped geodatabase on PW? Also, could you please provide a path for the document? Thanks so much!

Susie

From: Armenio, Maribeth [mailto:Maribeth.Armenio@stantec.com] 
Sent: Thursday, January 15, 2015 12:09 PM
To: Susan Foster
Cc: Haptemariam, Alex
Subject: RE: Updated GIS

Hi Susie,

Thanks for clarifying things with me yesterday over the phone. I have updated ProjectWise using another employee’s account here. The geodatabase is called 2015-01-15-Co CE-STN-Submission#2. Only one site was reshaped (for reference – CE-144) and the rest of the sites were noted for Future Consideration. Let me know if you need anything else or if something didn’t come through properly. Thanks a lot!

Maribeth Armenio
Engineering Project Specialist
Stantec
6110 Frost Place Laurel MD 20707-2927
Phone: (240) 542 - 3085
Maribeth.Armenio@stantec.com

The content of this email is the confidential property of Stantec and should not be copied, modified, retransmitted, or used for any purpose except with Stantec's written authorization. If you are not the intended recipient, please delete all copies and notify us immediately.

 Please consider the environment before printing this email. 

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Tuesday, January 13, 2015 4:47 PM
To: Armenio, Maribeth
Cc: Haptemariam, Alex
Subject: RE: Updated GIS

Maribeth,

Thanks you for your email – as discussed with  Alex and Neftalem and noted in the original email, these are not concept design sites. Alex was involved in the conversation with Neftalem when the sites were discussed. I am attaching the original email with instructions on viewing these and how to proceed with revisions. Please let me know if you are unable to access the data. If you could post the revised sites/statuses on PW as directed in the original email, that’d be great. 

Thank you very much, and have a good evening!

Susie

From: Armenio, Maribeth [mailto:Maribeth.Armenio@stantec.com] 
Sent: Tuesday, January 13, 2015 4:39 PM
To: Susan Foster
Cc: Haptemariam, Alex
Subject: FW: Updated GIS

Hi Susie,

Neftalem is out of the office for a couple more weeks so I will take a swing at your question but let me know if you need other information. I believe the only site we did a concept design for that was also effected by a future tree planting site on our near our BMP footprint is CE-027 . We did modify the footprint of the site to allow an ~8’ buffer between the tie in locations and tree location extent and meet ESDv requirements. If this does not appear to be addressed in the GIS files that were submitted to Projectwise, let me know. 

Thanks!
Maribeth Armenio
Engineering Project Specialist
Stantec
6110 Frost Place Laurel MD 20707-2927
Phone: (240) 542 - 3085
Maribeth.Armenio@stantec.com

The content of this email is the confidential property of Stantec and should not be copied, modified, retransmitted, or used for any purpose except with Stantec's written authorization. If you are not the intended recipient, please delete all copies and notify us immediately.

 Please consider the environment before printing this email. 

From: Haptemariam, Alex 
Sent: Tuesday, January 13, 2015 4:10 PM
To: Armenio, Maribeth
Subject: FW: Updated GIS

Meribeth,
I am not sure if you remember this, did you guys reshape  the sites to avoid the conflict?

Alex Haptemariam
Senior Project Manager

**Comment by SRF-NMP** [comment]
Files are not viewable on PW. Followed up 2014/01/30. Kerry, I'll keep you updated!

From: Susan Foster 
Sent: Friday, January 30, 2015 10:51 AM
To: 'Gravunder, Maribeth'
Subject: RE: Updated GIS

Maribeth,

I’m still unable to find a file with the 10 reshaped sites/new statuses. The only file here has 188 shapes and nothing has changed. Is this the correct file? The updated file should only have the ten shapes in the Issue that are either reshaped or have status changes.

Thanks,

Susie

From: Gravunder, Maribeth [mailto:Maribeth.Gravunder@stantec.com] 
Sent: Thursday, January 22, 2015 9:18 AM
To: Susan Foster
Subject: RE: Updated GIS

Hi Susan,

I did edit those files so it should be correct. I will have Neftalem take care of this when he comes in on Monday the 26th if that is OK with your timeline.

Sorry for the inconvenience!

Maribeth Gravunder
Engineering Project Specialist
Stantec
6110 Frost Place Laurel MD 20707-2927
Phone: (240) 542 - 3085
Maribeth.Gravunder@stantec.com

**Comment by SRF-NMP** [comment]
Consultant just emailed me a revised gdb, but it only contains one site (appears to be EFF_BMP_PLANNED_ID 0e70ab6d-aaff-4078-b76a-cfc687621f36  -  CE-144), that has been reshaped. They say that all others in this Issue have either been moved to FC or RC at the FI stage. However, I am still seeing these footprints in EFF_BMP_PLANNED from the 2014_Stormwater_Tree_Conflicts_Database.zip that was provided today with statues of recommended for restoration. Kerry, could you check the status of the remaining 9 EFF_BMP_PLANNED_IDs in this Issue, to verify their statuses? They only provided me with one site in their .gdb ID mentioned above). I can request them to provide the statuses for the remaining nine sites if the changes are still not being reflected in your DB from their last submission.  Email chain below.

From: Negussie, Neftalem [mailto:neftalem.negussie@stantec.com] 
Sent: Monday, February 02, 2015 5:02 PM
To: Susan Foster
Subject: Conflicts updated

Hey Susan;
I am just getting back into rhythm and catching up with everything. When you get a chance tomorrow, take a look at the attached GIS database and let me know if it will solve the conflict we have with the Tree sites. Most of the BMP’s that were flagged for conflict were either removed from consideration or placed in future consideration during the FI process and the “Opportunities” shapefile has been updated to reflect that. Only one BMP was reshaped so that it will not conflict with Tree planting sites (CE-144) and I have included the reshaped site footprint (approximate). Let me know if it is helpful at all. Thank you. 

Note: the attached file contains the geodatabase mentioned. Just rename the extension to “.zip” instead of “.piz” and it should work. 

Neftalem Negussie
Sr. Water Resources Engineer
Stantec
Phone: (301) 982-2868
neftalem.negussie@stantec.com

**Comment by kerrymcmahon** [comment]
I have updated the footprints to FC and the issue is closed.
