### ISSUE TITLE
ISSUE_FR_009 2014-12-03 FR County - JMT Stormwater Recommended site conflict with LUCHANGE sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#12]
**WHAT** - There are 8 planned stormwater sites in FREDERICK county that are "recommended for restoration" after a desktop review by JMT.

**CONFLICT** -  LUCHANGE_BMP sites that are "construction complete," "Needs Remediatii

**ACTION NEEDED** -  Stormwater teams must rework the three sites that are overlapping planted tree sires 100122UT and  100123UT.
There are three that conflict with tree sites listed as NOT BUILT, please verify with tree team.
There are two that are listed as "Needs Replanting" under contract AT9555124

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_FR_009

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Tree Team,
1. STRU_IDs 100079UT and 100055UT are listed as NP - "Replanting needed based on Spring 2014 field inspections - 6/24/2014" - what is status of these? Is the entire footprint reflective of actual tree planting boundaries?
2. STRU_ID 100133UT is listed as NB - "ENTIRE SITE HAS BEEN RELOCATED to MD 100 exit 3, along the ramp to Snowden River Parkway from MD 100 - AT5025282 Replacement Site" - what is status of these? 
Thanks in advance for your reply!

**Comment by nbyers1** [comment]
Susan,
1. Sites that are 'NP' do not necessarily reflect the tree planting boundaries - STRU_ID 100079UT in the database was not edited to show field-verified boundaries, while STRU_ID 100055UT does match the field-verified boundaries. However, the boundaries shown in LUCHANGE_BMP should significantly impact your SWM designs. Sites that are 'NP' have less than 50 trees per acre and are not counted for credit in the modeling baseline, so they are fully available to the Stormwater team.
2. I'm looking into 100133UT and will comment again when I've found out what's going on there.

**Comment by nbyers1** [comment]
Hi Susan,

It looks like 100133UT was never built. I can't find documentation as to why, and I'll keep looking to see if I can, but for now know that that area should be available to the Stormwater team.

**Comment by SRF-NMP** [comment]
Natalie,
1. Since STRU_IDs 100079UT and 100055UT are listed as NP, the EFF_BMP_PLANNED potential BMP shapes associated with them do not need to be modified by the consultant, despite the boundaries shown in LUCHANGE_BMP, correct? 
2. Thanks - I will not have the consultant reshape these sites that area associated with 100133UT.

**Comment by nbyers1** [comment]
Susan,
1. Correct, your consultant does not need to reshape the potential BMP shapes associated with the NP sites.
2. I'm not sure if there's been a misunderstanding here - since 100133UT (the tree site) was never built, the consultant should not need to reshape the SWM sites in the area.

-Natalie

**Comment by SRF-NMP** [comment]
Natalie,

Thanks! I have notified the consultant (email below) to revise shapes of the BMP sites conflicting with STRU_IDs 100122UT and 100123UT (only three sites: EFF_BMP_PLANNED_IDs fd1f6e59-0f07-46d7-a8d8-d6fef5a3d580, 546c2b2f-382b-4f9c-a733-992d0c68b29b, and  63909491-f4bf-4d75-a581-e8617220362a),since the other BMP sites are associated with either NP or NB tree areas. 
Re: 2. above, correct - as mentioned above, I did not have the consultant reshape the sites that were associated with 100133UT.

Kerry, these three  mentioned above conflict with tree sites. The rest should not be considered conflicts anymore due to their association with the NB and NP areas.

Thanks! 
Susie

Email to consultant:
From: Susan Foster 
Sent: Friday, December 19, 2014 5:03 PM
To: (SMiller@jmt.com)
Cc: Kristin Langway
Subject: Frederick County Gr1-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Scott,

Good afternoon! I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants of conflicts so that they are able to reshape their potential BMP footprints to accommodate the tree site so as to avoid a conflict, and to be aware of nearby tree planting areas. These conflicting sites are tracked as “Issues,”(which are groups of sites) and I am passing them along to the consultants for resolution. It is important to note that none of these potential BMP sites have gone to the concept design phase. A group of three potential BMP sites identified through your desktop evaluation conflict with tree planting areas. Since these BMP sites are within existing tree planting contracts, the potential BMP footprints must be reshaped by the consultant in order to avoid a conflict with the tree planting area footprint.  If a potential BMP site cannot be reshaped to accommodate the tree site, then the BMP site must be reclassified as future consideration. The reshaped BMP sites (or BMP sites that are unable to be reshaped, but have been moved to future consideration) must then be submitted through ProjectWise in order to update the database. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for  viewing/evaluating the possible reshaping of the BMP. The GIS potential BMP footprint and tree shapes are included in the feature classes (link below) for evaluation. 

Procedure:
1.       Download GIS file from ProjectWise: 2014-12-04_Fr_Co_Gr2-JMT_Tree_Conflict_Issue_FR_009.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Frederick\Gr2-JMT\07-GIS\2014-12-04_Fr_Co_Gr2-JMT_Tree_Conflict_Issue_FR_009.gdb.zip)
2.       Open ArcMap and add GIS data to view the following feature classes:
   a.       LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.      ISSUE_FR_009:  A group of potential BMP sites that are in conflict – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
                                                               i.       

c.       TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.       Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the overlapping tree site boundary, and different green hatches to differentiate between the two tree areas per my preference for the example).
2.       Zoom to each EFF_BMP_PLANNED_ID within the Issue.
3. ```
     Evaluate nature of conflict – below is an example of a conflict with graphic shown:
   ```
   
   a.       EFF_BMP_PLANNED_ID: fd1f6e59-0f07-46d7-a8d8-d6fef5a3d580
   NATURE OF CONFLICT (consultant to evaluate): Potential BMP site (in red outline) overlaps with tree site in LUCHANGE_BMP (tree site that is within a contract – densely hatched green and white area with green outline labeled with STRU_ID 100123UT). Although this is also overlapping with TREE_SITE_SELECTION (less densely hatched green and white area with a degree of transparency) - not currently under contract because these are possible tree planting areas), the potential BMP footprint must be reshaped to accommodate the shape of LUCHANGE_BMP (because this is under contract). Please reshape potential BMP site if possible. If not possible, then move this potential BMP site to future consideration and make appropriate updates in GIS. Please keep in mind any clearances that potential BMPs may need in relation to the tree site before finalizing the revised footprint. It is advised to maintain a 20’ minimum clearance to the tree site footprint. If there is no overlap of a potential BMP with a tree planting area, please be aware of the nearby tree planting area for future reference.
4. ```
     Determine a resolution: If the potential BMP footprint can be reshaped, the consultant must revise the shape in GIS. Again, if the potential BMP site is NOT able to be reshaped to accommodate the tree site, then it must be reclassified as future consideration within GIS. All changes must be posted on ProjectWise. Please email me when the changes have been posted, and also cc Kristin Langway (KLangway@sha.state.md.us).
   ```

Please let me know if you have any questions. Thank you for your work in helping us avoid tree conflicts! Have a great weekend!

Thanks,

Susie

Susan Foster
Phone: 410-771-9808, ext. 237
sfoster@nmpengineering.com

***_PLEASE NOTE**_*
NMP will be closed December 25, 2014 through January 2, 2015 (reopening on Monday January 5, 2015). 
Please coordinate with your NMP contact should you need something before COB on December 23, 2014. 
Otherwise, NMP wishes everyone a Happy Holiday.

**Comment by SRF-NMP** [comment]
Consultant has acknowledged receipt but has not yet returned the three shape revisions. Email below:

From: Miller, Scott [mailto:SMiller@jmt.com] 
Sent: Friday, December 19, 2014 5:32 PM
To: Susan Foster
Cc: Kristin Langway; Li, Houng
Subject: RE: Frederick County Gr1-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Thanks Susan.  We will let you know if we have any questions after reviewing your e-mail.

Johnson, Mirmiran & Thompson, Inc.
 “An Employee Owned Company”

Scott A. Miller, P.E. 
Water Resources
P. 410-316-2202
M. 443-438-0792

**Comment by kerrymcmahon** [comment]
I have updated all but the three as "resolved"

**Comment by SRF-NMP** [comment]
Followed up with consultant regarding these three sites. Email below. 

From: Susan Foster 
Sent: Thursday, January 22, 2015 10:28 AM
To: 'Miller, Scott'
Cc: Kristin Langway; Li, Houng
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Scott,

Good morning! I am following up regarding the tree conflicts. Were you able to revise the footprints and/or recommendations? Please let me know if you have any questions!

Thanks,

Susie

**Comment by SRF-NMP** [comment]
Consultant deleted shapes instead of reshaping/reclassifying them. They replied in December, but I was unable to locate original email.I replied clarifying what is needed. Email below to Houng (I mistakenly called him Li!). 

From: Susan Foster 
Sent: Friday, January 23, 2015 9:31 AM
To: 'Li, Houng'
Cc: Kristin Langway; Miller, Scott; Pickering, Douglas
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Li,

Good morning, and thanks for your email. It is actually the future stormwater locations (the EFF_BMP_PLANNED IDs in the link in the original email) that need modification/classification change (to future consideration if it cannot be reshaped). If a potential BMP footprint overlaps with a tree planting site and cannot be reshaped, then it needs to be reclassified as future consideration (not deleted). If it can be reshaped to accommodate the tree site, then it should be physically reshaped with a new footprint submitted. I know there is a lot of information below, and the tree info can be confusing. Please let me know if you have any questions! There is no need for a cover letter/transmittal – if you could upload it to PW, that would be great. 

Again, please call/email if you have any questions or anything is unclear. Strangely, I have no record of receiving your email attached from December – my apologies!

Thanks again,

Susie

From: Li, Houng [mailto:HLi@jmt.com] 
Sent: Thursday, January 22, 2015 10:35 AM
To: Susan Foster; Miller, Scott
Cc: Kristin Langway
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Susan,

Please see the attached email and let me know if it addressed your comments.  Thank you,

Houng

Johnson, Mirmiran & Thompson, Inc.
 “An Employee Owned Company”

Houng Li
Water Resources
72 Loveton Circle
Sparks, MD 21152
P. 410-316-2343
F. 410-472-2200
hli@jmt.com

**Comment by SRF-NMP** [comment]
Discussed with Houng Li of JMT on phone to clarify. He or Doug Pickering (GIS Analyst) will address three shapes in this issue and notify me when they are updated. Email chain below. Kerry, I'll notify you when the shapes are available.

From: Susan Foster 
Sent: Friday, January 23, 2015 3:41 PM
To: 'Pickering, Douglas'
Cc: Li, Houng; (SMiller@jmt.com); Kristin Langway
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Doug,

I just spoke with Houng (I think he will update you soon). Only this feature class with three sites needs to be edited (not the entire original database from September). 

Thanks!

Susie

From: Pickering, Douglas [mailto:DPickering@jmttg.com] 
Sent: Friday, January 23, 2015 3:18 PM
To: Susan Foster; Li, Houng
Cc: Kristin Langway; Miller, Scott
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Ok, I think I see what happened here.  The issue that Houng was bringing up is that the schema for the feature class that we submit containing the BMP footprints (from the original supplied template) is different from the schema of the feature class containing the 3 conflicting footprints which you provided (ISSUE_FR_009).  As the screenshot below shows, we do not have the “SITE_STATUS” field in the original template (although we do see it in the footprint conflicts feature class that your provided).  This means that we currently have nowhere to indicate that the footprint should be for Future Consideration.  The original template feature classes only had the “RECOMMENDATION” field in the Stormwater_BMP_Opportunities feature class that could be used to indicate future consideration.

So… in summary, we can add the SITE_STATUS field to our BMP footprint schema (with the associated domain) based on how it appears in the feature class you provided with the conflicts and then either mark these footprints for future consideration or adjust them to remove the conflicts.
From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Friday, January 23, 2015 2:57 PM
To: Pickering, Douglas; Li, Houng
Cc: Kristin Langway; Miller, Scott
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Doug,

No problem! Yes – the three BMP footprints (EFF_BMP_PLANNED_IDs in the ISSUE_FR_009 feature class -  group of potential BMP sites that are in conflict with the trees in contracts LUCHANGE) need to either be reshaped to accommodate the tree footprint or reclassified as future consideration if they cannot be reshaped to accommodate the tree site. The three in this feature class were identified as tree conflicts, so they were separated out. 

Thanks!

Susie

From: Pickering, Douglas [mailto:DPickering@jmttg.com] 
Sent: Friday, January 23, 2015 2:51 PM
To: Susan Foster; Li, Houng
Cc: Kristin Langway; Miller, Scott
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

I’m sorry, I’m mistaken, it’s not the tree site selection feature class.  Are you saying that we should edit the ISSUE_FR_009 feature class that was supplied?

From: Pickering, Douglas 
Sent: Friday, January 23, 2015 2:48 PM
To: 'Susan Foster'; Li, Houng
Cc: Kristin Langway; Miller, Scott
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Susie,

The table you show and the highlighted portion from the original email appear to be extracts from the tree site selection feature class (the schema matches).  I was under the impression that we were not editing that feature class.  Your email from this morning indicates that it’s the Future_Stormwater_Locations feature class that we should be changing the SITE_STATUS field for (which does not exist in our version of the schema from September).

Doug

Doug Pickering
GIS Analyst

JMT Technology Group
“An Employee Owned Company”
dpickering@jmttg.com  

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Friday, January 23, 2015 2:40 PM
To: Li, Houng
Cc: Pickering, Douglas; Kristin Langway; Miller, Scott
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Houng,

Thanks - in the link in the original email below (highlighted in yellow) that contains the feature class with the three potential shapes identified that conflict with trees from December 19, there is a field called “SITE_STATUS” (expanded screen shot view below with headings from the original screenshot of the EFF_BMP_PLANNED_IDs in original email). Are you able to locate and edit this field/these shapes? 

Thanks! I’ll be here until about 5:30pm if you have any more questions.

Susie

From: Li, Houng [mailto:HLi@jmt.com] 
Sent: Friday, January 23, 2015 2:25 PM
To: Susan Foster
Cc: Pickering, Douglas; Kristin Langway; Miller, Scott
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Susie,

Is this the “SITE_STATUS” a new field in the future stormwater location feature class?  We do see it in the most recent “Stormwater BMP Opportunities - GIS Desktop and Field Review Workflow” (Page 30).  But when we got the FR Co database in September, there is no such a field for the feature class in the database we received.  Please look at the screen shot below:

So do we add the field to the feature class ourselves?  Should we populate for other DE sites?  I remember Kristin used to tell us not to go back to finished work due to protocol revisions.  As such, I copied the email to her, Scott, and our GIS person Doug to get them involve.  Please let us know your decision.

Thanks,

Houng 

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Friday, January 23, 2015 11:52 AM
To: Li, Houng
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Houng,

Thanks for getting back to me so quickly and explaining the IT issues! Regarding editing the future stormwater locations feature class, do you see the “SITE_STATUS” column/pull-down? There should be an option for “future consideration.” Please let me know if that doesn’t work or you have any other questions.

Thanks!

Susie

From: Li, Houng [mailto:HLi@jmt.com] 
Sent: Friday, January 23, 2015 11:33 AM
To: Susan Foster
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Susie,

That is all right.  Both my first and last names are unique here so either would do.  I think I also know why you have not received my email in December.  We have a sub-consultant on this job, we recently found that the sub sometimes sent us compressed database files in the working progress but we did not even know.  I guess it is because of the IT policies of either the sender or the recipient (or both sides) that would falsely identify the compressed database files as unrelated to bussiness and block the files.  From now on I would upload to PW and send you a notification email so we can avoid that.

For the three sites you listed, I have a question.  I understand that you want me to keep their future stormwater locations (and not to delete them) and reshape them, which I know how to do.  But if I need to re-classify them for FC, what should I do in the database?  The future stormwater location feature has attributes like OBJECT ID, SHAPE, COMMENT, DESIGN_Subcategory, Shape_Length, Shape_Area, and Site_number, but I did not find a place to input FC.  Instead, the Stormwater_BMP_Opportunities feature has a place to input FC (the attribute RECOMMENDATION), that is why I input FC there in the first place.  Please let me know what I should do.

Thank you,

Houng

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Friday, January 23, 2015 9:36 AM
To: Li, Houng
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Houng,

I apologize – I mistakenly called you Li!

**Comment by SRF-NMP** [comment]
Consultant has revised recommendations for the three sites in this Issue to FC. Kerry, the updated GIS data is here:

pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Frederick\Gr2-JMT\07-GIS\2014-12-04_Fr_Co_Gr2-JMT_Tree_Conflict_Issue_FR_009_JMT_Jan 2015.gdb.zip

Email chain below.

From: Susan Foster 
Sent: Thursday, January 29, 2015 6:10 PM
To: 'Li, Houng'
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Houng,

Thank you very much for revising the recommendations. I appreciate it!  Everything looks good.

Thanks again!

Susie

From: Li, Houng [mailto:HLi@jmt.com] 
Sent: Monday, January 26, 2015 8:04 AM
To: Susan Foster
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Susan,

I have explained to Doug and placed the revision file in the same folder.  Thanks for your patience.

Best,

Houng

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Friday, January 23, 2015 3:41 PM
To: Pickering, Douglas
Cc: Li, Houng; Miller, Scott; Kristin Langway
Subject: RE: Frederick County Gr2-JMT Potential BMP Conflicts with Tree Planting Areas: Issue_FR_009

Doug,

I just spoke with Houng (I think he will update you soon). Only this feature class with three sites needs to be edited (not the entire original database from September). 

Thanks!

Susie

**Comment by kerrymcmahon** [comment]
The data has been updated to reflect the changes and this issue is now closed.
