### ISSUE TITLE
ISSUE_AA_015 - 2014-12-15 AA County - Stormwater Recommended for Restoration sites that conflict w/ TREE SITE SELECTION recommended sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#17]
**WHAT** - There are 33 planned stormwater sites in AA county that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. 

**CONFLICT** -  TREE_SITE_SELECTION sites that are "recommended for restoration"

**ACTION NEEDED** -  Both teams must rework sites that are overlapping, or leave the shapes and change to future consideration.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_AA_015

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by nbyers1** [comment]
Hi all,

The majority of the conflicts have been resolved by changing our tree sites to Future Consideration or Removed from Consideration as appropriate.

Two tree sites have been adjusted based on field visits in such a way that they will no longer conflict with the proposed SWM BMPs. These edits will be available when the AA mapbook database is posted, expected the end of this week (1/9/15). These sites are:

-0200972UT
-0200916BUT

Two tree sites planned to be planted this spring (Spring 2015) are in conflict with proposed SWM BMP sites. One of these is under contract, the other is a 'reserve' site - that means that it will be planted if acreage is lost at other sites due to ROW or utility problems. Since the proposed SWM BMPs in conflict with these sites are bioswales and it looks like it would take only minor readjustments to avoid the conflict, we are in the process of adjusting the shapes for these sites. The sites are:

-0200556AUT (STRU_ID = 020105UT)
-0201629AUT and BUT (Combined into STRU_ID 020119UT)

SWM team, can you please advise regarding how much of a buffer would be appropriate alongside your bioswale shapes?

Thanks!
Natalie

**Comment by SRF-NMP** [comment]
Hi Natalie,
Where are "reserve" sites located in the database?
Thanks!
Susie

**Comment by nbyers1** [comment]
Hi Susie,

Reserve sites should be located in LUCHANGE_BMP. I admit I'm not entirely familiar with how they are typically entered - I'll look into it - but in the case of the site mentioned above, the site is in LUCHANGE_BMP with a TMDL_ACTIVITY.Status of 'Proposed' and the LUCHANGE_BMP.GEN_COM says that it is a RESERVE site for Spring 2015.

Hope that helps!

-Natalie

**Comment by SRF-NMP** [comment]
Thanks, Natalie - I don't think these appeared in LUCHANGE before. I will get back to you with an appropriate buffer.

**Comment by nbyers1** [comment]
Update: Although they have not yet been loaded into the database, the site shapes mentioned as adjusted based on field visits in my previous comment can be viewed in the geodatabase posted to PW at the following location:
pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\Tree Plantings\District 5\2015 Contract\01_SiteSelection\GIS\AA_FA14_toBHuber_01082015.zip

**Comment by SRF-NMP** [comment]
Natalie, a 50' buffer is advised. Is this possible?  Thanks!

**Comment by kerrymcmahon** [comment]
This issues is now closed.
