### ISSUE TITLE
ISSUE_HA_016 -  2014-12-16 HA County - Stormwater Recommended for Restoration sites that conflict w/ LUCHANGE

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#18]
**WHAT** - There are 3 planned stormwater sites in Harford county that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. 

**CONFLICT** -  LUCHANGE_BMP sites 

**ACTION NEEDED** -  These are very minor conflicts. Stormwater can investigate the status of each site and reshape as needed.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_HA_016

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Kerry,

Thanks – the data in this Issue is not loading into GIS – could you please upload again? I’m getting a warning that GIS cannot load the data. There are 3 blank rows, so at least the correct number of fields are there! Thanks!

**Comment by SRF-NMP** [comment]
1/3 conflicts is with a "not built" tree site. The remaining two (39f3c5c4-621e-4a73-96a5-3cdec42c5b92 and f211ce89-f31e-49e5-892e-ef8626d3d85f have been sent to the consultant (out of office until Jan. 5). These are conflicts with disconnection of non-rooftop areas. Email below:
From: Susan Foster 
Sent: Tuesday, December 23, 2014 3:49 PM
To: Labuda, George R.
Cc: Kristin Langway
Subject: Harford County Gr2-WMA Potential BMP Conflicts with Tree Planting Areas: Issue_HA_016

George,

I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants of conflicts so that they are able to reshape their potential BMP footprints to accommodate the tree site so as to avoid a conflict, and to be aware of nearby tree planting areas. These conflicting sites are tracked as “Issues,”(which are groups of sites) and I am passing them along to the consultants for resolution. It is important to note that none of these potential BMP sites have gone to the concept design phase. A group of two potential BMP sites identified through your desktop evaluation conflict with tree planting areas. Since these BMP sites are within existing tree planting contracts, the potential BMP footprints must be reshaped by the consultant in order to avoid a conflict with the tree planting area footprint.  If a potential BMP site cannot be reshaped to accommodate the tree site, then the BMP site must be reclassified as future consideration. The reshaped BMP sites (or BMP sites that are unable to be reshaped, but have been moved to future consideration) must then be submitted through ProjectWise in order to update the database. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for  viewing/evaluating the possible reshaping of the BMP. The GIS potential BMP footprint and tree shapes are included in the feature classes (link below) for evaluation. 

Procedure:
1.       Download GIS file from ProjectWise: 2014-12-23_HA_Co_Gr2-WMA_Tree_Conflict_Issue_HA_016.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Harford\Gr2-WMA\07-GIS\2014-12-23_HA_Co_Gr2-WMA_Tree_Conflict_Issue_HA_016.gdb.zip
   a.       LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.      ISSUE_HA_016:  A group of potential BMP sites that are in conflict – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
                                                               i.       

c.       TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.       Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the overlapping tree site boundary, and different green hatches to differentiate between the two tree areas per my preference for the example).
2.       Zoom to each EFF_BMP_PLANNED_ID within the Issue.
3. ```
     Evaluate nature of conflict – below is an example of a conflict with graphic shown:
   ```
   
   a.       EFF_BMP_PLANNED_ID: f211ce89-f31e-49e5-892e-ef8626d3d85f
   NATURE OF CONFLICT (consultant to evaluate): Potential BMP site that is classified as a disconnection of non-rooftop credit (in red outline) overlaps with tree site in LUCHANGE_BMP (tree site that is within a contract – densely hatched green and white area with green outline labeled with STRU_IDs 100123UT and 120098UT). Although this is also overlapping with TREE_SITE_SELECTION (less densely hatched green and white area with a degree of transparency) - not currently under contract because these are possible tree planting areas), the potential BMP footprint must be reshaped to accommodate the shape of LUCHANGE_BMP (because this is under contract). Please reshape potential BMP site if possible (in this example, it appears a disconnection credit could be achieved in the open space towards the southern middle part of the site, but other areas within the BMP footprint cannot achieve a disconnection credit due to the overlap with the LUCHANGE footprint). If it is not possible to reshape, then move this potential BMP site to future consideration and make appropriate updates in GIS/submit on PW. 
4. ```
     Determine a resolution: If the potential BMP footprint can be reshaped, the consultant must revise the shape in GIS. Again, if the potential BMP site is NOT able to be reshaped to accommodate the tree site, then it must be reclassified as future consideration within GIS. All changes must be posted on ProjectWise. Please email me when the changes have been posted, and also cc Kristin Langway (KLangway@sha.state.md.us).
   ```

Please let me know if you have any questions. Thank you for your work in helping us avoid tree conflicts! 
Thanks,

Susie

Susan Foster
Phone: 410-771-9808, ext. 237
sfoster@nmpengineering.com

***_PLEASE NOTE**_*
NMP will be closed December 25, 2014 through January 2, 2015 (reopening on Monday January 5, 2015). 
Please coordinate with your NMP contact should you need something before COB on December 23, 2014. 
Otherwise, NMP wishes everyone a Happy Holiday.

**Comment by SRF-NMP** [comment]
Followed up with consultant. Email below.

From: Susan Foster 
Sent: Friday, January 23, 2015 9:47 AM
To: Labuda, George R.
Subject: RE: Harford County Gr2-WMA Potential BMP Conflicts with Tree Planting Areas: Issue_HA_016

George,

Good morning! I’m following up to see if you were able to revise these shapes discussed below.  Please let me know if you have any questions.

Thanks,

Susie

**Comment by SRF-NMP** [comment]
Consultant will submit revisions with FI/SSR/GIS data package 2014/02/03. Email below.

From: Susan Foster 
Sent: Friday, January 23, 2015 10:49 AM
To: 'Labuda, George R.'
Cc: Kristin Langway (KLangway@sha.state.md.us); Marschke, Glenn W.
Subject: RE: Harford County Gr2-WMA Potential BMP Conflicts with Tree Planting Areas: Issue_HA_016 - WM No. 214006.0019

George,

Thanks for replying so quickly – yes, the shape revisions can be included in your next submittal package.

Thanks again!

Susie

From: Labuda, George R. [mailto:GLabuda@wallacemontgomery.com] 
Sent: Friday, January 23, 2015 10:04 AM
To: Susan Foster
Cc: Kristin Langway (KLangway@sha.state.md.us); Marschke, Glenn W.
Subject: RE: Harford County Gr2-WMA Potential BMP Conflicts with Tree Planting Areas: Issue_HA_016 - WM No. 214006.0019

Susie, 

We are scheduled to submit our Field Investigation Site Search Report and all corresponding updated GIS data on February 3rd. My plan was to revise the shapes discussed below and include them as part of the next submittal package. Is this acceptable? 

Thanks

George Labuda, P.E.
410.494.9093

**Comment by kerrymcmahon** [comment]
I will  close the issue now, since conflicts will be re-run when I do the data load.
