### ISSUE TITLE
ISSUE_HA_017 - 2014-12-16 HA County - Stormwater Recommended for Restoration sites that conflict w/ LUCHANGE

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#19]
**WHAT** - There are 29 planned stormwater sites in Harford county that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. 

**CONFLICT** -  TREE_SITE_SELECTION recommended or reserved sites 

**ACTION NEEDED** -   Stormwater and tree teams can investigate the status of each site and reshape or change status as needed.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_HA_017

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Kerry,

Thanks! There are only 29 IDs in this dataset – are there supposed to be 36 as mentioned in the Issue?

**Comment by SRF-NMP** [comment]
Confirmed that there are only 29 sites. 
Tree Team: 
1. Several EFF_BMP_PLANNED IDs that overlap with SS_IDs 1200097UT, 1200107UT, and 1200122UT are "under review" - per the "Tree Status Terminology" document, this could mean that they are actively being designed in a design concept or on hold. What is the status of these? These overlap with potential bioswale sites. SInce they are not in LUCHANGE, can they be moved to FC?
1. SS_ID 1200114UT that overlaps with EFF_BMP_PLANNED_ID e45f245f-515b-4868-98e7-b2cd30d627c7 (potential bioswale) is "under contract," but this overlapping footprint is still in tree site selection. There is a neighboring footprint to the south in LUCHANGE with the same SS_ID with a different footprint.  Is the footprint in tree site selection a part of the LUCHANGE footprint, but not updated? If it is not under contract, can this be moved to FC in order to allow a BMP to be built?
2. Can the following SS_IDs be moved to FC? 1200366BUT, 1200266BUT, 1200265BUT, 
   1200064BUT, 1204056BUT, 1204055BUT, 1200487BUT, 1200451AUT, 1200137UT, 1200481AUT, 1200299AUT, 1200095UT, 1204246BUT, 1200282BUT, 1200302BUT (very large - possibly rework to allow BMP footprint with generous clearance since this is a preliminary BMP footprint), 1200480BUT, 1204381UT, 1200286BUT, 1200682BUT, 1200333AUT

Thank you very much in advance! I'll be in communication with the consultant re: their EFF_BMP_PLANNED IDs in this Issue that overlap with these after I have confirmation regarding the above tree sites.

**Comment by nbyers1** [comment]
Hi Susan,
1. Sites 1200097UT and 1200107UT are not in our records anywhere as scheduled to be planted; I've found that there is quite a number of sites in the database that are erroneously 'Under Review'. These two sites have been changed to FC. Site 1200122UT is under review as a relocation site for this spring (STRU_ID 120133UT and 120134UT).  We will reshape 120134UT, which is currently app. 4' away from the adjacent potential bioswale, if we are provided with an appropriate buffer to use.
   1. The Tree Site Selection file for 1200114UT has been split into AUT and BUT to better reflect the LUCHANGE footprint. This should no longer turn up as conflict. 
   2. With the exception of the SS_IDs dealt with at the end of this paragraph, all of the requested sites, as well as several additional conflicting sites, were changed to FC. The exceptions are as follows:
      -1200302BUT - This is a potential relocation for the Spring 2015 planting season. It has a very minor conflict with the adjacent bioswale. We would like to reshape the site to accommodate both the SWM BMP and the trees.
      -1200480BUT - This is also a potential relocation for the Spring 2015 planting season. It has a very minor conflict with the adjacent bioswale. We would like to reshape the site to accommodate both the SWM BMP and the trees.

When you know what buffer we should implement along the bioswales, please let us know and we will adjust these two sites.

Thanks,
Natalie

**Comment by SRF-NMP** [comment]
Natalie,
Thanks for taking the time to look into these and reshape!  We are suggesting a 50' buffer. 
Thanks!
Susie

**Comment by nbyers1** [comment]
A 50' buffer has been applied to 1200480BUT and 1200302BUT. This edit is in the RKK version of the TMDL database.

**Comment by SRF-NMP** [comment]
Thanks, Natalie!

**Comment by kerrymcmahon** [comment]
This issue is now closed.
