### ISSUE TITLE
BA County MTI Site 063 - Conflict with contracted tree site

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#2]
**ISSUE**: BA_MTI_063 Concept Design conflict with contracted tree site.

Several emails have been exchanged - resolution unknown.

**Map here**: pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-10-16-Tree_Conflicts_BA_MTI\MTI_BA_063_CONFLICT_MAP.pdf

**CONCEPT SITE HERE**:
pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-10-16-Tree_Conflicts_BA_MTI\BA-063_Footprint.zip

**Comment by SRF-NMP** [comment]
Email chain through 10/30:

Thu 10/30/2014 4:38 PM
Kristin Langway klangway@nmpengineering.com
RE: Tree/SWM Coordination
To Kate Gordon kgordon@rkk.com
Cc Kerry McMahon KMcMahon@sha.state.md.us; Brittany Huber Brittany.Huber@kci.com; Susan Foster SFoster@nmpengineering.com; Jason Alwine jalwine@gfnet.com; Sean C. Punte Sean.Punte@stvinc.com
Kate,
As a follow up to my email from earlier today, my designer has developed concept grading, sizing computations, and resulting tmdl credits for the two Baltimore County sites (33 & 63) where we currently have conflicts.
In summary, we would be able to achieve impervious credit for 1.1 acres and 0.98 acres of existing untreated impervious by the proposed facilities at BA-63 and 33, respectively.  
Thanks,
Kristin
Kristin S. Langway, P.E.

---

Hi Kristin, 

OK - I understand if this site is too far along to abandon. I think we can probably work something out. We actually just found out about a site nearby that we can use as a relocation site this spring. 

Also, from the aerial it looks like there are some existing trees on the site that are in the grading footprint. Where would you be mitigating for the tree impacts? On site after grading is completed?
- Kate

---

KATE GORDON, PWS
Project Scientist

---

From: "Kristin Langway" klangway@nmpengineering.com
To: "Kate Gordon" kgordon@rkk.com
Cc: "Kerry McMahon" KMcMahon@sha.state.md.us, "Brittany Huber" Brittany.Huber@kci.com, "Susan Foster" SFoster@nmpengineering.com
Sent: Wednesday, October 29, 2014 12:44:16 PM
Subject: RE: Baltimore County Group 1 - Tree/SWM Coordination
Hi Kate,
Since this site is not to be constructed until this spring, is there any way we can work together to adjust the footprints of each of our sites to make the best use of the site?  We could coordinate on what is needed and how things can be adjusted?
As you are finding it is difficult to secure sites, we are having the same issue and I’m reluctant to completely give up on a site with potential treatment, especially a site we’ve been working on for a while now.
Let me know when you’d like to get together to discuss.  Better sooner rather than later as my consultant is working on concept designs at this time.
Thanks,
Kristin

   Kristin S. Langway, P.E.
  Water Resources Project Manager

---

From: Kate Gordon [mailto:kgordon@rkk.com] 
Sent: Tuesday, October 28, 2014 12:51 PM
To: Kristin Langway
Cc: Kerry McMahon; Brittany Huber; Susan Foster
Subject: Re: Baltimore County Group 1 Comments for Concept Design

Hi Kristin, 

That footprint is way bigger than I anticipated based on the shape in EFF_BMP_PLANNED. Please don't proceed with design. Since this tree site is in an active tree planting contract, is scheduled to be planted in the spring, and is in Baltimore County, where we have had difficulty finding suitable relocation sites, proceeding with SWM here would cause a number of problems for the tree program. 

Let me know if you have any questions. 

Thanks!

---

KATE GORDON, PWS
Project Scientist

---

From: "Kristin Langway" klangway@nmpengineering.com
To: "Kate Gordon" kgordon@rkk.com
Cc: "Kerry McMahon" KMcMahon@sha.state.md.us, "Brittany Huber" Brittany.Huber@kci.com, "Susan Foster" SFoster@nmpengineering.com
Sent: Tuesday, October 28, 2014 6:59:44 AM
Subject: FW: Baltimore County Group 1 Comments for Concept Design
Kate,
Please see the attached footprint from MTI for BA-063.  Please let me know if you are able to work around this BMP.
Thanks,
Kristin
Kristin S. Langway, P.E.

---

From: Baker, Amanda N.[SMTP:ANBAKER@MCCORMICKTAYLOR.COM] 
Sent: Monday, October 27, 2014 9:40:28 AM 
To: Kristin Langway 
Cc: klangway@nmpengineering.com 
Subject: RE: Baltimore County Group 1 Comments for Concept Design 
Auto forwarded by a Rule 
Kristin,

No problem. Sorry I didn’t respond Thursday or Friday, I was off. If you want this uploaded to PW I can do so now.

Cheers,
Amanda

---

From: Kristin Langway [mailto:KLangway@sha.state.md.us] 
Sent: Thursday, October 23, 2014 8:45 AM
To: Baker, Amanda N.
Cc: klangway@nmpengineering.com
Subject: RE: Baltimore County Group 1 Comments for Concept Design

Amanda,
That’s great, thanks for doing that so quickly.  Please send in GIS shape file, that will be adequate to show the tree team.
Thank you!
Kristin
Kristin Langway, P.E.

---

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Wednesday, October 22, 2014 5:55 PM
To: Kristin Langway
Cc: klangway@nmpengineering.com
Subject: RE: Baltimore County Group 1 Comments for Concept Design

Kristin,

I just finished the concept grading and computations on BA-063 and wanted to know if you need the footprint in GIS or MicroStation for the tree folks.

Cheers,
Amanda

**Comment by SRF-NMP** [comment]
MTI will be submitting concept design (CD) 2014/12/19.

**Comment by kerrymcmahon** [comment]
The concept design has been entered. The tree site needs modification. What is the status of communication regarding this?

**Comment by nbyers1** [comment]
The tree site is being modified to fully avoid the provided footprint. The adjusted site geometry will be provided to Brittany in the next few days.

**Comment by nbyers1** [comment]
Site BA00106 (the tree site conflicting with BA-063) has been modified in the RKK version of the TMDL database to fully avoid the provided footprint.

**Comment by kerrymcmahon** [comment]
I have verified this shape change and the issue is now closed.
