### ISSUE TITLE
ISSUE_BA_018 - 2014-12-18- BA County - Stromwater Recommended for Restoration site that conflicts w/ LUCHANGE

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#20]
**WHAT** - There is 1 planned stormwater sites in Baltimore County that is "recommended for restoration" after desktop evaluation - it has not been visited in the field. 

**CONFLICT** -  LUCHANGE_BMP site that is under contract for 2016. 

**ACTION NEEDED** -  This is a very minor conflict with plenty of room in the area to reshape. Please submit the shape to the stormwater team for reshaping and resubmission.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_BA_018

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**Comment by SRF-NMP** [comment]
Kerry, this for Group 3 - RKK, correct?

**Comment by kerrymcmahon** [comment]
Yes - RKK/RJM

**Comment by SRF-NMP** [comment]
Thanks - is there an ID for this?  There is no ID in the attribute table.

**Comment by kerrymcmahon** [comment]
I pulled this from their data delivery, because I was trying to get this back to Kristin ASAP. You should not need an ID for the consultant, just the shape, since it's their shape.

**Comment by SRF-NMP** [comment]
Thanks, Kerry! Email to the consultant (below) has been sent for this one site.

From: Susan Foster 
Sent: Thursday, December 18, 2014 5:52 PM
To: Seyed Saadat
Cc: Kristin Langway
Subject: BA County Gr3-RKK Potential BMP Conflict with Tree Planting Areas: Issue_BA_018

Seyed,

Good afternoon! I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants of conflicts so that they are able to reshape their potential BMP footprints to accommodate the tree site so as to avoid a conflict, and to be aware of nearby tree planting areas. These conflicting sites are tracked as “Issues” (which is a group of sites) and I am passing them along to the consultants for resolution. It is important to note that none of these potential BMP sites have gone to the concept design phase. Only one potential BMP sites identified through your desktop evaluation conflicts with tree planting area. Since this BMP site is within an existing tree planting contract footprint, the potential BMP footprint must be reshaped by the consultant in order to avoid a conflict with the tree planting area footprint.  If a potential BMP site cannot be reshaped to accommodate the tree site, then the BMP site must be reclassified as future consideration. The reshaped BMP sites (or BMP sites that are unable to be reshaped, but have been moved to future consideration) must then be submitted through ProjectWise in order to update the database. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for  viewing/evaluating the possible reshaping of the BMP. The GIS potential BMP footprint and tree shapes are included in the feature classes (link below) for evaluation. 

Procedure:
1.       Download GIS file from ProjectWise: 2014-12-18_Ba_Co_Gr3-RKK_Tree_ISSUE_BA_018.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr3-RKK\07-GIS\2014-12-18_Ba_Co_Gr3-RKK_Tree_ISSUE_BA_018.gdb.zip)
2.       Open ArcMap and add GIS data to view the following feature classes:
   a.       LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.      ISSUE_BA_018:  A group of potential BMP sites that are in conflict (only one in this group) – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
                                                               i.       

c.       TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.       Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the overlapping tree site boundary, and different green hatches to differentiate between the two tree areas per my preference for the example).
2.       Zoom to each OBJECTID within the Issue. **This is normally denoted as EFF_BMP_PLANNED ID; however, this database only identifies the one site as an OBJECTID.**
3. ```
     Evaluate nature of conflict – below is an example of a conflict with graphic shown:
   ```
   
   a.       OBJECTID: 1
   NATURE OF CONFLICT (consultant to evaluate): Potential BMP site (in blue outline) overlaps with tree site in LUCHANGE_BMP (tree site that is within a contract – densely hatched green and white area with green outline). Although this is also overlapping with TREE_SITE_SELECTION ( less densely hatched green and white area - not currently under contract because these are possible tree planting areas), the potential BMP footprint must be reshaped to accommodate the shape of LUCHANGE_BMP (because this is under contract). Please reshape potential BMP site if possible. If not possible, then move this potential BMP site to future consideration and make appropriate updates in GIS. Please keep in mind any clearances that potential BMPs may need in relation to the tree site before finalizing the revised footprint. It is advised to maintain a 20’ minimum clearance to the tree site footprint. If there is no overlap of a potential BMP with a tree planting area, please be aware of the nearby tree planting area for future reference.
4. ```
     Determine a resolution: If the potential BMP footprint can be reshaped, the consultant must revise the shape in GIS. Again, if the potential BMP site is NOT able to be reshaped to accommodate the tree site, then it must be reclassified as future consideration within GIS. All changes must be posted on ProjectWise. Please email me when the changes have been posted, and also cc Kristin Langway (KLangway@sha.state.md.us).
   ```

Please let me know if you have any questions. Thank you for your work in helping us avoid tree conflicts! 
Thanks,

Susie

Susan Foster
Phone: 410-771-9808, ext. 237
sfoster@nmpengineering.com

**Comment by SRF-NMP** [comment]
Steve Philips acknowledged receipt and will revise shape:

From: Steve Phillips [mailto:sphillips@rkk.com] 
Sent: Friday, December 19, 2014 10:20 AM
To: Susan Foster
Subject: Fwd: BA County Gr3-RKK Potential BMP Conflict with Tree Planting Areas: Issue_BA_018

Susan-
Thank you for the comment.  We will coordinate with NMP and get the updated shape back to SHA.  

Can you please be sure to send the e-mails to me for this task?  I will be the project manager for this task, as well as the other TMDL tasks assigned to RKK.  Feel free to CC Seyed.

Thanks,
Steve

**Comment by SRF-NMP** [comment]
Consultant has relocated the only conflicting site to the opposite side of the road. Email below. The reshaped site is located in this path:

pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr3-RKK\08-Submissions\2014-12-22-BA Co-CEM-Submission2-(gdb).zip

From: Steve Phillips [mailto:sphillips@rkk.com] 
Sent: Monday, December 22, 2014 5:10 PM
To: Susan Foster
Cc: Dori Shivers; Seyed Saadat; Kristin Langway; Nick Walls
Subject: Re: BA County Gr3-RKK Potential BMP Conflict with Tree Planting Areas: Issue_BA_018

Susan-
As requested CEM has revised the potential BMP conflict with the TMDL tree planting area as described below.  We have reviewed the revision and placed it on projectwise in the appropriate submission folder.  Please let me know if there are any other questions or concerns.

Thanks,

---

STEVEN PHILLIPS, P.E.
Project Manager, Water Resources

RK&K
81 Mosher Street
Baltimore, MD 21217

410.728.2900 P
410.728.2834 F
410.462.9369 D
www.rkk.com

**Comment by kerrymcmahon** [comment]
The site has been modified. Issue closed.

**Comment by kerrymcmahon** [comment]
QC'd and reconfirmed on 01/06
