### ISSUE TITLE
ISSUE_CE_022 - 2015-01-02 CE County - Concept Design finalized sites that conflict with TREE SITE SELECTION

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#21]
**WHAT** - There are 17  planned stormwater sites in Cecil county that are now completed for concept design

**CONFLICT** -  TREE_SITE_SELECTION 

**ACTION NEEDED** -   Tree team must zoom to each feature to identify any conflicts that may occur with sites that are being considered for future treatment (note, not all of these ocnflict, but I included them all)

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_CE_022

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by nbyers1** [comment]
All TREE_SITE_SELECTION polygons in conflict with ISSUE_CE_022 have been edited (in the RKK version of the TMDL database) to avoid conflict, with one exception.

SS_ID 0700071UT conflicts with STANTEC_CE-027. 0700071UT corresponds to STRU_ID 070034UT, which is a contracted tree site for the Spring 2015 planting season. 070034UT and STANTEC_CE-027 are approximately 10' apart. We expect to adjust 070034UT according to the typical 50' buffer, but are waiting to see whether we will have enough acreage to drop the entire site (since less than 0.1 acres are left after applying the buffer) or if we will need the remaining acreage.

**Comment by SRF-NMP** [comment]
Natalie,

Has the buffer been applied? This site is already in concept design and cannot be altered.Thanks!

**Comment by nbyers1** [comment]
Susan, 

The buffer has not yet been applied - as I stated, we are waiting to see whether we will buffer or entirely drop the site (based on whether we have enough relocation elsewhere). Either way, the site will not be in conflict with the SWM site.

**Comment by SRF-NMP** [comment]
Natalie, thanks for the update!

**Comment by kerrymcmahon** [comment]
This issue is now closed
