### ISSUE TITLE
ISSUE_CE_023: 2015-02-02 Cecil County- Brudis Stormwater Recommended site conflict w/ Tree Site Selection Recommended Sites 

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#26]
**WHAT** - There are 7 planned stormwater sites in Cecil county that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. Consultant created over 600 recommended stormwater sites therefore reshaping or removing from consideration should be possible.  

**CONFLICT** -  TREE_SITE_SELECTION sites that are in "recommended"

**ACTION NEEDED** -  Stormwater/Tree teams **must** rework sites that are overlapping, and be aware of sites that are within 15 feet of existing plantings.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name is PLANNING_CONFLICT_LOCATIONS, The issue number is ISSUE_CE_023.

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The PLANNING_CONFLICT_LOCATION feature represents the location of the conflict. These **must** be viewed with the TREE SITE SELECTION and EFF_BMP_PLANNED featureclassses.

**Comment by SRF-NMP** [comment]
Since these are noted to be in a tree contract, should they be in LUCHANGE? Or are they about about to be put into a contract?

**Comment by kerrymcmahon** [comment]
I am not sure where it is noted that these are in a contract. Please identify where this is shown. As far as I can tell, these are just in Tree Site Selection as "Recommended"

**Comment by nbyers1** [comment]
Kerry, the initial issue description you give above indicates that the sites are in a contract for 2015 under the 'CONFLICT' heading.

**Comment by SRF-NMP** [comment]
Kerry,

Since I will be having the consultant simply  change the status of these to FC, do you want an official submittal from them on PW with status changes (no reshaping at this stage)? Alternatively, I could simply notify them, and notify you once I have confirmed that they have acknowledged and made the status change. Do you have a preference, since they won't be reshaping anything at this stage? Thanks!

**Comment by kerrymcmahon** [comment]
No, they do not need to resubmit. I will trust that you will have them modift the data accordingly, and I will also do this on my end. This issue is now closed.

**Comment by SRF-NMP** [comment]
Thanks, Kerry! I notified the consultant. Email below.

From: Susan Foster 
Sent: Thursday, February 12, 2015 3:52 PM
To: 'SAshraf@brudis.com'
Subject: Cecil County Gr2- BAI Potential BMP Conflicts with Tree Planting Areas (Tree Site Selection):

Saleem,

I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants of conflicts so that they can be aware of nearby tree planting areas. A group of seven potential BMP sites identified through your desktop evaluation conflict with tree site selection planting areas. Since these BMP sites are within boundaries of potential tree plantings that may soon be put in a contract, the potential BMP footprints should be reclassified as Future Consideration by the consultant in order to avoid a conflict with the tree planting area footprint. The following seven sites below (identified as EFF_BMP_PLANNED_IDs in the database) should be reclassified as Future Consideration in your database so as to avoid a conflict. This will be updated in the SHA-maintained database, so no additional submittal with these status changes is required. 

b753ee9f-2744-4300-ba52-1779606275f7
98dd3281-abaf-4439-adde-01c77d167693
673d8bdc-9df6-4258-a07a-840a6ac0cd99
628bb4d9-75cd-40da-bd3d-d5be4f0ef012
b3033e38-f35e-4b87-b753-24f007c32374
1e535aab-e89c-4fab-b00e-b9e50d7b4b1f
263372e8-01e4-4147-912e-be24b84d9db1

Please let me know if you have any questions!

Thanks,

Susie

**Comment by SRF-NMP** [comment]
Consultant has acknowledged and will change. Email below:

From: Saleem Ashraf [mailto:sashraf@brudis.com] 
Sent: Wednesday, March 04, 2015 10:51 AM
To: Susan Foster
Subject: RE: Cecil County Gr2- BAI Potential BMP Conflicts with Tree Planting Areas (Tree Site Selection):

Hi Susan,

I was out of office for the last few weeks.  We will reclassify the BMPs, as indicated in your email below. 

Saleem
