### ISSUE TITLE
ISSUE_AA_001:    2014-11-17 AA County - Stormwater Concept conflict w/ Tree Site Selection

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#3]
**WHAT** - There are 11 planned stormwater sites in AA county that have moved into concept design phase.

**CONFLICT** - Tree Site Selection sites that are "recommended for restoration."

**ACTION NEEDED** - Tree team must modify site selection polygons to accommodate and either edit in checkout or submit new shapes to Brittany for loading.

**SHAPE LOCATION** - The geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_AA_001 

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Tree Team, have these been reshaped?

**Comment by nbyers1** [comment]
I am in the process of addressing these sites and will provide an update later this afternoon. Thanks!

**Comment by nbyers1** [comment]
All Tree Site Selection sites in conflict with the AA_01 SWM sites have been changed to Future Consideration or Removed from Consideration. (These edits are in the RKK version of the TMDL database.)

As a side note: Two of the tree sites in conflict (0201834UT and 0201668UT) were removed due to being in MdTA ROW. I would suspect that the SWM BMPs that intersect with these sites should be reconsidered as well due to conflict with MdTA ROW.

**Comment by kerrymcmahon** [comment]
This issues is now closed.
