### ISSUE TITLE
ISSUE_AA_002:  2014-11-17 AA County - Stormwater Recommended Sites conflict w/ Tree SITE SELECTION

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#4]
**WHAT** - There are 34 planned stormwater sites in AA county that are "recommended for restoration".

**CONFLICT** - Tree Site Selection sites that are "recommended for restoration."

**ACTION NEEDED** - Tree and Stormwater teams must work together on these sites on a case-by-case basis. Because each site is only in a planning stage, modification by either team may be necessary. 

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_AA_002

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014-11-17-Unresolved_Conflicts.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Since these are in Tree Site Selection and "recommended for restoration," if the Tree team could please move these to future consideration and not be moved to a contract so that the SW teams can evaluate these sites for possible BMPs, that'd be great Thanks!

**Comment by nbyers1** [comment]
These sites have mostly been moved by Brittany to 'Future Consideration' in the database. Since these sites have been field visited but that data has not yet been loaded into the database, there are a few exceptions:

a) sites that have already been determined to be inappropriate for planting have been updated to 'Removed from Consideration'

b) sites that have been significantly altered due to field visits and where the final planting area will not impact the planned SWM BMP have not yet been updated in the database. The new geometry is scheduled to be posted to PW by Dec. 19. The sites in this category are: (reference number is the TreeSiteSelection.SS_ID)
-0200715UT
-0201422BUT
-0201443UT
-0201323UT
-0201736UT

**Comment by kerrymcmahon** [comment]
Thanks Natalie. I will close this issue upon confirmation and updating my piece.

**Comment by nbyers1** [comment]
FYI - the AA mapbook data posting has been postponed. We are currently aiming for the end of this week (1/9/15).

**Comment by nbyers1** [comment]
Update: Although they have not yet been loaded into the database, the site shapes mentioned as altered due to field visits in my previous comment can be viewed in the geodatabase posted to PW at the following location:
pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\Tree Plantings\District 5\2015 Contract\01_SiteSelection\GIS\AA_FA14_toBHuber_01082015.zip
