### ISSUE TITLE
ISSUE_AA_003:  2014-11-17  AA County - Stormwater Recommended Sites conflict w/ LUCHANGE_BMP

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#5]
**WHAT** - There are 3 planned stormwater sites in AA County (along 295 median) that are "recommended for restoration."

**CONFLICT** - LUCHANGE_BMP (tree assets) that have status "needs remediation."

**ACTION NEEDED** - Although this is an existing tree site, if it needs remediation, there may be room to work in the 3 stormwater BMPs.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_AA_003

**NOTE** - The issues feature represents that stormwater footprint. These must be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Email resolution below - these should be RC.

Thu 10/30/2014 10:42 AM
Susan Foster SFoster@nmpengineering.com
RE: NMP - Three sites on 295 - 
To: Kerry McMahon Kerry.McMahon@kci.com
Cc: Kristin Langway klangway@nmpengineering.com; Kate Gordon kgordon@rkk.com

Kerry,
You are correct - these sites are indeed from the April 2014 submission, before we had tree conflicts.  They are also on top of a SWMFAC layer, so they should be RC.
Thanks,
Susie

From: Kerry McMahon [mailto:KMcMahon@sha.state.md.us] 
Sent: Thursday, October 23, 2014 2:34 PM
To: Kristin Langway; Kate Gordon; Susan Foster
Subject: NMP - Three sites on 295 - 

These came from NMP’s submission 1, I think possibly prior to use even having tree conflicts on our radar. Since I don’t have site names to give you, here is from the original submission:

Please note, that when NMP submitted revisions, these sites were not included in their field visit, so they are still only at the desktop level.  They are “recommended for restoration.”

The tree site is a 2011 site listed as “needing remediation.” 

Please address the attached map and let me know the outcome.

Kerry McMahon
GIS Analyst 

TMDL Team Consultant for
Maryland State Highway Administration
Office of Environmental Design

Maryland now features 511 traveler information! 
Call 511 or visit: www.md511.org

**Comment by kerrymcmahon** [comment]
These are updated in the database and the issue is considered resolved.

**Comment by kerrymcmahon** [comment]
QC'd and reconfirmed on 01/06/2015
