### ISSUE TITLE
ISSUE_CH_004: 2014-11-17  CH County - Stormwater Recommended sites conflict w/ LUCHANGE sites in contract

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#6]
This is per Kate's email on 11-17-2014:

**WHAT** - There are 3 planned stormwater sites in CHARLES county that are "recommended for restoration" and are being examined to go into concept design.

**CONFLICT** -  LUCHANGE_BMP sites that are in a contract for 2016

**ACTION NEEDED** - Tree and Stormwater teams must work together on these sites on a case-by-case basis. Conflicts are minor and can be reworked

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_CH_004

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014-11-17-Unresolved_Conflicts.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by kerrymcmahon** [comment]
Thanks for setting this up – from this set of three sites, two (EFF_BMP_PLANNED_ID: 6a988d18-a52d-4ab8-a9c1-4db41a2b1fa7 - SITE_NAME: CH_KCI_054 and EFF_BMP_PLANNED_ID: 9bf1cdd1-7ef3-462f-97ec-e31b67537931 – SITE_NAME CH_KCI_053) possibly qualify for existing grass channel credits (with backup BMPs as grass swales), but what appears to be their footprints are very thin slivers – are there any other footprints associated with these backup BMPs? As of now, a possible existing grass swale would not be considered a conflict – I’ll note this in the issue.
Also, for EFF_BMP_PLANNED_ID: 82df1183-c843-43b0-93c5-f929c1eda431, who made the GEN_COM – was it KCI? I’m not seeing why this tree site needs reshaping.

**Comment by kerrymcmahon** [comment]
We are assuming these to be resolved, but will provide maps if these sites go to concept, so that consultants avoid nearby planting.

**Comment by SRF-NMP** [comment]
Consultant notified of nearby tree plantings:

From: Kristin Langway 
Sent: Thursday, December 04, 2014 4:05 PM
To: 'James Kester'
Cc: Kristin Langway; 'Susan Foster'; Kerry McMahon
Subject: SHA TMDL SWM SS & CD Charles County Group 1 - Sites for Concept Design

Hi Jim,
We have completed the review of your FI/SVR resubmission and determined the 30 sites to move in to the concept design phase of this task.  I have placed the list in your correspondence folder on PW.  Please review the sites and let me know if you have any questions/concerns about any of them.

Please note that Sites 53 and 54 are very close to tree planting sites that are also in design. Please avoid impacting these tree sites if at all possible.  If you find that it is not possible to do that, please let me know sooner rather than later and I can discuss the use of this site with the tree group.  For reference, see attached IFB (Invitation for Bid for the tree sites, PAGE 315 has sites names 0801133UT-A, B and C).  You may use the EFF_BMP_PLANNED featureclass in the geodatabase here to see where these sites are located. 2014-12-03-Unresolved_Conflicts.zip

Again, please take some time and review these sites, then let me know by Tuesday of next week if a due date of February 24, 2015 is acceptable to you for the concept design packages.

Thanks for your hard work on this.
Kristin

Kristin Langway, P.E.
Consultant for the Maryland State Highway Administration
TMDL Team
Office of Environmental Design
klangway@sha.state.md.us

**Comment by kerrymcmahon** [comment]
This issue has been updated in the database as resolved.

**Comment by kerrymcmahon** [comment]
QC'd and re-confirmed on 01/06/2015
