### ISSUE TITLE
ISSUE_BA_005: 2014-11-19 BA County - Stormwater Recommended site conflict w/ LUCHANGE sites Construction Complete 2011

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#7]
**WHAT** - There are 11 planned stormwater sites in BALTIMORE county that are "recommended for restoration" after a field evaluation - and will be examined to go into concept design.

**CONFLICT** -  LUCHANGE_BMP sites that are "construction complete" for 2011

**ACTION NEEDED** -  Stormwater teams must rework sites that are overlapping, and be aware of sites that are within 15 feet of existing plantings.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_BA_005

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014-11-19-Unresolved_Conflicts.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Is this for Group 2 - JEI?

**Comment by kerrymcmahon** [comment]
Yes, Jacobs

**Comment by kerrymcmahon** [comment]
These sites can move forward, they just need to be aware of nearby plantings.

**Comment by nbyers1** [comment]
If it is useful to know - the LUCHANGE polygon (STRU_ID 030011UT) that impacts the SWM footprint with site name BAGr2-PEI-065 has a status of 'Not Built', so there is no need to adjust the SWM design to avoid it.

**Comment by SRF-NMP** [comment]
Informed consultant of tree sites near potential BMP sites to be aware of for future reference:
Fri 12/5/2014 1:36 PM
Baltimore County Gr2-JEI Potential BMPs Location Near Tree Planting Areas: Issue_BA_005
To: ' (Gabe.Makhlouf@jacobs.com)'
Cc: Kristin Langway klangway@nmpengineering.com

Gabe,

Good afternoon! I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants so that they are aware of nearby tree plantings (that are not currently conflicting with a potential BMP footprint). In some cases where there is overlap of potential BMP site footprints with tree planting area footprints that are in a contract, the consultant would have to reshape the footprint of the potential BMP. 

These potentially conflicting sites are grouped and tracked as “Issues,” and I am passing them along to the consultants for resolution. It is important to note that none of these potential BMP sites have gone to the concept design phase. A group of eleven potential BMP sites identified through your desktop evaluation are located within close proximity to tree planting areas. Since these BMP sites are near existing tree planting areas that are within a contract, consultants must be aware of these footprints in order to avoid a conflict with the tree planting area footprint, should the potential BMP proceed to design.  There is no need to reshape any of the potential BMP sites referenced in this Issue at this point. Due to a 20’ buffer that has been included in the tree planting area footprint, you will see overlap for a few potential BMPs – despite this overlap, there is no need to reshape the potential BMP sites since the buffer has been included.  I am passing these along to you (viewable in GIS) so that you are able to view the proximity of the potential BMP to the tree planting area and can be aware of the tree planting areas for future reference. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for viewing the footprints of the potential BMPs and tree planting areas. The GIS potential BMP footprints and tree planting area shapes are included in the feature classes for evaluation (link below). 

Procedure for viewing:
1.  Download GIS file from ProjectWise:  2014-12-04_ Ba_Co_Gr2-JEI_Tree _Conflict_ISSUE_BA_005.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr2-JEI\07-GIS\2014-12-04_ Ba_Co_Gr2-JEI_Tree _Conflict_ISSUE_BA_005.gdb.zip)
2.  Open ArcMap and add GIS data provided in the link above to view the following feature classes:
   a.  LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.  ISSUE_BA_005:  A group of potential BMP sites that are nearby – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
i.   

c.  TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.  Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the nearby tree site boundary, and different green hatches to differentiate between the two tree areas per my preference).
2.  Zoom to each EFF_BMP_PLANNED_ID within the Issue.
3.  View footprints of the potential BMPs and tree planting areas – below is an example with graphic shown:
   a.  EFF_BMP_PLANNED_ID: 88f67bd8-5c14-46f5-99d9-6ac8cf4c2410
   NATURE OF POTENTIAL CONFLICT: Potential BMP site (in red outline) is near a tree planting area in LUCHANGE_BMP (tree site that is within a contract – densely hatched green and white area with green outline). For this potential BMP site, no reshaping is necessary – simply note the proximity for future reference. Although this is overlapping with TREE_SITE_SELECTION (less densely hatched green and white area - not currently under contract because these are possible tree planting areas), no reshaping is necessary. It is simply provided to differentiate between the states of tree planting areas.
4.  Please confirm that these sites will be noted as being located in close proximity to tree planting areas for future reference. 

Please let me know if you have any questions. Thank you for your work in helping us avoid future tree conflicts! 
Thanks,

Susie

Susan Foster
Phone: 410-771-9808, ext. 237
sfoster@nmpengineering.com

**Comment by SRF-NMP** [comment]
Thanks, Natalie! It appears that a BMP could fit in this area given the buffer that is included (the overlap is at the upstream end of the potential BMP footprint anyway), so I didn't ask the consultant to reshape that one in the email above that I just sent them.

**Comment by SRF-NMP** [comment]
Consultant is aware of proximity of nearby tree plantings:
Mon 12/8/2014 1:28 PM
Nader Mahmoudpour nmahmoudpour@primeeng.com
To: Ferrari, Nicholas Nicholas.Ferrari@jacobs.com
Cc: Makhlouf, Gabe Gabe.Makhlouf@jacobs.com; Susan Foster SFoster@nmpengineering.com; KLangway@sha.state.md.us

Thank you Nicholas for letting me know and sending the updated files. 

Regards,
Nader

From: Ferrari, Nicholas [mailto:Nicholas.Ferrari@jacobs.com] 
Sent: Monday, December 08, 2014 11:48 AM
To: Nader Mahmoudpour
Cc: Makhlouf, Gabe; SFoster@nmpengineering.com; KLangway@sha.state.md.us
Subject: RE: Baltimore County Gr2-JEI Potential BMPs Location Near Tree Planting Areas: Issue_BA_005

Nader,

FYI we received information regarding proposed BMP conflicts with areas identified for tree planting (see Susan Foster’s email below).

The following BMP sites are within close proximity of tree planting areas:    
1.  BAGr2-JEG-030
2.  BAGr2-PEI-049
3.  BAGr2-PEI-060
4.  BAGr2-PEI-063
5.  BAGr2-PEI-065
6.  BAGr2-PEI-067
7.  BAGr2-PEI-069
8.  BAGr2-PEI-070
9.  BAGr2-PEI-071
10. BAGr2-PEI-074
11. BAGr2-PEI-097

We have updated the comment sections of the combined Jacobs and Prime “Future_Stormwater_Locations_BA_JEG” shapefile to note potential conflicts with proposed planting sites. We will use this information moving forward into Concept Design.

Below are FTP links to the updated Field Investigation GDB as well as the Tree Conflict GDB provided by Susan Foster:

Tree Conflicts: https://jftt.jacobs.com/download.aspx?ID=4c8d1c8d-1597-4f8a-80eb-94df0afad3b5&RID=7ebcab63-2301-4820-91b3-1cede0c43b5f

Updated Jacobs/Prime GDB:  https://jftt.jacobs.com/download.aspx?ID=eef9568f-867a-4e22-90d1-b091cf6fda8a&RID=6d801d42-f006-4ab5-a681-f1987a9fe1d1

Sincerely,

Nicholas Ferrari
Jacobs
Civil Engineering | Highway Design
410.230.6637
410.837.3277 fax
Nicholas.Ferrari@jacobs.com

**Comment by kerrymcmahon** [comment]
I have updated the database to consider this issue closed, though it will be monitored.

**Comment by kerrymcmahon** [comment]
QC'd and reconfirmed on 01/06/2015 - however, conflict will be re-evaluated upon concept design.
