### ISSUE TITLE
ISSUE_BA_006: 2014-11-24 BA County - Jacobs Stormwater Recommended site conflict w/ LUCHNAGE sites Comstruction Complete

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#8]
**WHAT** - There are 3 planned stormwater sites in BALTIMORE county that are "recommended for restoration" after a desktop

**CONFLICT** -  LUCHANGE_BMP sites that are "construction complete" 

**ACTION NEEDED** -  Stormwater teams must rework sites that are overlapping, and be aware of sites that are within 15 feet of existing plantings.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_BA_006

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014-11-24-Unresolved_Conflicts.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Is there any buffer included in these tree shapes in LUCHANGE, or are these the actual tree footprints?

**Comment by kerrymcmahon** [comment]
The footprints are ALWAYS the actual footprints. The buffer previously mentioned refers to the proximity at which the intersect was run, meaning instead of looking only for stormwater and tree sites that are touching, we look at stormwater and tree sites that are NEAR each other, by about 10-15 feet, since the footprints are subject to change.

**Comment by SRF-NMP** [comment]
Consultant has been informed of need to evaluate tree conflicts:
Tue 12/9/2014 2:51 PM
Susan Foster SFoster@nmpengineering.com
Baltimore County Gr2-JEI Potential BMPs Locations Conflicting with Tree Planting Areas: Issue_BA_006
To  (Gabe.Makhlouf@jacobs.com)
Cc Kristin Langway klangway@nmpengineering.com
Gabe,

Thanks for passing along the previous tree Issue (Issue_BA_005 - proximity to tree planting areas) to your team yesterday.  An additional group of three potential BMP sites has been identified in a separate Issue (ISSUE_BA_006) that conflicts with existing tree planting areas. The potential BMP sites included in the PW link below will need to be evaluated in order to determine if the potential BMP footprints can possibly be reshaped in order to accommodate the tree site so as to avoid a conflict. If a potential BMP site cannot be reshaped to accommodate the tree site, then the BMP site must be reclassified as future consideration. The reshaped BMP sites (or BMP sites that are unable to be reshaped, but have been moved to future consideration) must then be submitted through ProjectWise in order to update the database. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for  viewing/evaluating the possible reshaping of the BMP. The GIS potential BMP footprint and tree shapes are included in the attached feature classes for evaluation. 

Procedure:
1.  Download GIS file from ProjectWise:  2014-12-09_Ba_Co_Gr2-JEI_Tree_Conflict_ISSUE_BA_006.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr2-JEI\07-GIS\2014-12-09_Ba_Co_Gr2-JEI_Tree_Conflict_ISSUE_BA_006.gdb.zip)
2.  Open ArcMap and add GIS data to view the following feature classes:
   a.  LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.  ISSUE_BA_006:  A group of potential BMP sites that are in conflict – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
i.   

c.  TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.  Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the overlapping tree site boundary, and different green hatches to differentiate between the two tree areas per my preference).
2.  Zoom to each EFF_BMP_PLANNED_ID within the Issue.
3.  Evaluate nature of conflict – below is an example of a conflict with graphic shown:
   a.  EFF_BMP_PLANNED_ID: 2e3d01e4-b2b8-4c44-9229-6f72d5e5a77c
   b.  NATURE OF CONFLICT: Potential BMP site (in red outline) overlaps with tree site in LUCHANGE_BMP (STRU_ID 030004UT - tree site that is within a contract and is classified as construction complete – densely hatched green and white area). Although this is also overlapping with TREE_SITE_SELECTION ( less densely hatched green and white area - not currently under contract because these are possible tree planting areas), the potential BMP footprint must be reshaped to accommodate the shape of LUCHANGE_BMP (because this is under contract). Please rework potential BMP site if possible. If not possible, then move this potential BMP site to future consideration and make appropriate updates in GIS so that the database is updated. Please keep in mind any clearances that potential BMPs may need in relation to the tree site before finalizing the revised footprint. It is advised to maintain a 20’ minimum clearance to the tree site footprint. If there is no overlap of a potential BMP with a tree planting area, please be aware of the nearby tree planting area.
4.  Determine a resolution: Again, if the potential BMP footprint can be reshaped, the consultant must revise the shape in GIS. If the potential BMP site is NOT able to be reshaped to accommodate the tree site, then it must be reclassified as future consideration within GIS in order to update the database. All changes must be posted on ProjectWise. Please email me when the changes have been posted, and also cc Kristin Langway (KLangway@sha.state.md.us).

Please let me know if you have any questions. Thank you for your work in helping avoid tree conflicts! 

Thanks,

Susie

**Comment by SRF-NMP** [comment]
Consultant has updated two shapes that conflict, and noted third as FC (email below). Kerry, the two reshaped sites look good - let me know if you have any problems with the data (located below). EFF_BMP_PLANNED_ID d63395ff-06cc-4be6-b2ca-0574bb96aa4f was unable to be reshaped, but consultant has reclassified it as FC. This is not a part of the updated DB below-should I have them provide the revised status of FC as part of this DB, or is this an update you'd prefer to make in the DB?
Thanks!
 pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr2-JEI\08-Submissions\2014-12-10-BA Co DE-JEG-03\2014-12-10-BA Co DE-JEG-03.gdb.z

---

From: Ferrari, Nicholas [mailto:Nicholas.Ferrari@jacobs.com] 
Sent: Wednesday, December 10, 2014 1:31 PM
To: Susan Foster; KLangway@sha.state.md.us
Cc: Makhlouf, Gabe; Nader Mahmoudpour nmahmoudpour@primeeng.com (nmahmoudpour@primeeng.com)
Subject: RE: Baltimore County Gr2-JEI Potential BMPs Locations Conflicting with Tree Planting Areas: Issue_BA_006

Susie and Kristen,

The BMPs identified with potential tree planting conflicts have been revised. 
• The first BMP could not be reshaped to mitigate impacts to proposed tree planting site BA036D, therefore it was marked for Future Consideration. 
• The second and third BMPs, which conflicted with tree planting sites NB06.1 and SB10 respectively, have been revised to  remove impacts. 

A GDB containing only the revised files from the previous DE evaluation has been uploaded to ProjectWise: 2014-12-10-BA Co DE-JEG-03

Sincerely,

Nicholas Ferrari
Jacobs
Civil Engineering | Highway Design
410.230.6637
410.837.3277 fax
Nicholas.Ferrari@jacobs.com

**Comment by kerrymcmahon** [comment]
Thank you for the revised data. I have made the updates in the database and this issue is now considered resolved and closed.

**Comment by kerrymcmahon** [comment]
QC;d and reconfirmed on 01/06/2015
