### ISSUE TITLE
ISSUE_BA_007: 2014-11-24 BA county - MTI - Stormwater Recommended site conflict with LUCHANGE sites Construction Complete

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#9]
**WHAT** - There are 11 planned stormwater sites in BALTIMORE county that are "recommended for restoration" after a desktop review

**CONFLICT** -  LUCHANGE_BMP sites that are "construction complete" 

**ACTION NEEDED** -  Stormwater teams must rework sites that are overlapping, and be aware of sites that are within 15 feet of existing plantings.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_BA_007

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Informed consultant of conflicts:
Thu 12/4/2014 5:50 PM
from: Susan Foster
Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007
To: 'Baker, Amanda N.' ANBaker@mccormicktaylor.com
Cc: Kristin Langway klangway@nmpengineering.com
Amanda,

Good afternoon! I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants of conflicts so that they are able to reshape their potential BMP footprints to accommodate the tree site so as to avoid a conflict, and to be aware of nearby tree planting areas. These conflicting sites are tracked as “Issues,” and I am passing them along to the consultants for resolution. It is important to note that none of these potential BMP sites have gone to the concept design phase. A group of eleven potential BMP sites identified through your desktop evaluation either conflict with tree planting areas or are located within close proximity to tree planting areas. Since these BMP sites are either within or nearby existing tree planting contracts, the potential BMP footprints must be reshaped by the consultant in order to avoid a conflict with the tree planting area footprint.  If a potential BMP site cannot be reshaped to accommodate the tree site, then the BMP site must be reclassified as future consideration. The reshaped BMP sites (or BMP sites that are unable to be reshaped, but have been moved to future consideration) must then be submitted through ProjectWise in order to update the database. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for  viewing/evaluating the possible reshaping of the BMP. The GIS potential BMP footprint and tree shapes are included in the attached feature classes for evaluation. 

Procedure:
1.  Download GIS file from ProjectWise:  2014-12-04 Ba Co Gr1-MTI Tree Conflict_ISSUE_BA_007.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr1-MTI\07-GIS\2014-12-04 Ba Co Gr1-MTI Tree Conflict_ISSUE_BA_007.gdb.zip)
2.  Open ArcMap and add GIS data to view the following feature classes:
   a.  LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.  ISSUE_BA_007:  A group of potential BMP sites that are in conflict – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
i.   

c.  TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.  Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the overlapping tree site boundary, and different green hatches to differentiate between the two tree areas per my preference).
2.  Zoom to each EFF_BMP_PLANNED_ID within the Issue.
3.  Evaluate nature of conflict – below is an example of a conflict with graphic shown:
   a.  EFF_BMP_PLANNED_ID: dcdbe306-b3a1-4d6e-b11a-6a3c4ece6571  
   NATURE OF CONFLICT: Potential BMP site (in red outline) overlaps with tree site in LUCHANGE_BMP (tree site that is within a contract – densely hatched green and white area). Although this is also overlapping with TREE_SITE_SELECTION ( less densely hatched green and white area - not currently under contract because these are possible tree planting areas), the potential BMP footprint must be reshaped to accommodate the shape of LUCHANGE_BMP (because this is under contract). Please rework potential BMP site if possible. If not possible, then move this potential BMP site to future consideration and make appropriate updates in GIS. Please keep in mind any clearances that potential BMPs may need in relation to the tree site before finalizing the revised footprint. It is advised to maintain a 20’ minimum clearance to the tree site footprint. If there is no overlap of a potential BMP with a tree planting area, please be aware of the nearby tree planting area.
4.  Determine a resolution: If the potential BMP footprint can be reshaped, the consultant must revise the shape in GIS. If the potential BMP site is NOT able to be reshaped to accommodate the tree site, then it must be reclassified as future consideration within GIS. All changes must be posted on ProjectWise. Please email me when the changes have been posted, and also cc Kristin Langway (KLangway@sha.state.md.us).

Please let me know if you have any questions. Thank you for your work in helping us avoid tree conflicts! 
Thanks,

Susie

Suan Foster
Phone: 410-771-9808, ext. 237
sfoster@nmpengineering.com

***_PLEASE NOTE**_*
NMP will be closed December 25, 2014 through January 2, 2015 (reopening on Monday January 5, 2015). 
Please coordinate with your NMP contact should you need something before COB on December 23, 2014. 
Otherwise, NMP wishes everyone a Happy Holiday.

**Comment by SRF-NMP** [comment]
Followed up with consultant:
From: Susan Foster 
Sent: Wednesday, December 24, 2014 4:27 PM
To: 'Baker, Amanda N.'
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Amanda, 

I just wanted to check in and make sure you received my email below from December 4 and find out when you will be able to submit the revisions.  Please let me know as soon as possible so that I can schedule the GIS team. Also, please let me know if anything was unclear or you had any questions.

Thanks and have a good holiday!

Susie

From: Susan Foster 
Sent: Thursday, December 04, 2014 5:50 PM
To: 'Baker, Amanda N.'
Cc: Kristin Langway
Subject: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Amanda,

Good afternoon! I’m working with Kristin on the TMDL program and assisting in coordination efforts to identify and resolve potential BMP conflicts with tree planting areas. I am notifying consultants of conflicts so that they are able to reshape their potential BMP footprints to accommodate the tree site so as to avoid a conflict, and to be aware of nearby tree planting areas. These conflicting sites are tracked as “Issues,” and I am passing them along to the consultants for resolution. It is important to note that none of these potential BMP sites have gone to the concept design phase. A group of eleven potential BMP sites identified through your desktop evaluation either conflict with tree planting areas or are located within close proximity to tree planting areas. Since these BMP sites are either within or nearby existing tree planting contracts, the potential BMP footprints must be reshaped by the consultant in order to avoid a conflict with the tree planting area footprint.  If a potential BMP site cannot be reshaped to accommodate the tree site, then the BMP site must be reclassified as future consideration. The reshaped BMP sites (or BMP sites that are unable to be reshaped, but have been moved to future consideration) must then be submitted through ProjectWise in order to update the database. Below I have listed descriptions for all items which you will be viewing, as well as an example procedure for  viewing/evaluating the possible reshaping of the BMP. The GIS potential BMP footprint and tree shapes are included in the attached feature classes for evaluation. 

Procedure:
1.  Download GIS file from ProjectWise:  2014-12-04 Ba Co Gr1-MTI Tree Conflict_ISSUE_BA_007.gdb.zip (pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr1-MTI\07-GIS\2014-12-04 Ba Co Gr1-MTI Tree Conflict_ISSUE_BA_007.gdb.zip)
2.  Open ArcMap and add GIS data to view the following feature classes:
   a.  LUCHANGE_BMP: a feature class showing the spatial extent of TMDL Activities that change the land use at that location. Land use change activities include but are not limited to, tree plantings, wetlands, and pavement removal. All sites in this feature class are under contract and are either approaching construction, under construction, or construction complete. These site locations should be considered final.

b.  ISSUE_BA_007:  A group of potential BMP sites that are in conflict – the Issue contains potential BMP sites identified as EFF_BMP_PLANNED_ID:
i.   

c.  TREE_SITE_SELECTION: A feature class showing the spatial extent of possible tree planting locations.
1.  Ensure that all of these are displayed with footprints visible in GIS (customize properties to display as desired – in the example graphic below, I have chosen a red outline with no fill for the potential BMP shape in order to view the overlapping tree site boundary, and different green hatches to differentiate between the two tree areas per my preference).
2.  Zoom to each EFF_BMP_PLANNED_ID within the Issue.
3.  Evaluate nature of conflict – below is an example of a conflict with graphic shown:
   a.  EFF_BMP_PLANNED_ID: dcdbe306-b3a1-4d6e-b11a-6a3c4ece6571  
   NATURE OF CONFLICT: Potential BMP site (in red outline) overlaps with tree site in LUCHANGE_BMP (tree site that is within a contract – densely hatched green and white area). Although this is also overlapping with TREE_SITE_SELECTION ( less densely hatched green and white area - not currently under contract because these are possible tree planting areas), the potential BMP footprint must be reshaped to accommodate the shape of LUCHANGE_BMP (because this is under contract). Please rework potential BMP site if possible. If not possible, then move this potential BMP site to future consideration and make appropriate updates in GIS. Please keep in mind any clearances that potential BMPs may need in relation to the tree site before finalizing the revised footprint. It is advised to maintain a 20’ minimum clearance to the tree site footprint. If there is no overlap of a potential BMP with a tree planting area, please be aware of the nearby tree planting area.
4.  Determine a resolution: If the potential BMP footprint can be reshaped, the consultant must revise the shape in GIS. If the potential BMP site is NOT able to be reshaped to accommodate the tree site, then it must be reclassified as future consideration within GIS. All changes must be posted on ProjectWise. Please email me when the changes have been posted, and also cc Kristin Langway (KLangway@sha.state.md.us).

Please let me know if you have any questions. Thank you for your work in helping us avoid tree conflicts! 
Thanks,

Susie

Suan Foster
Phone: 410-771-9808, ext. 237
sfoster@nmpengineering.com

***_PLEASE NOTE**_*
NMP will be closed December 25, 2014 through January 2, 2015 (reopening on Monday January 5, 2015). 
Please coordinate with your NMP contact should you need something before COB on December 23, 2014. 
Otherwise, NMP wishes everyone a Happy Holiday.

**Comment by SRF-NMP** [comment]
Consultant replied 2014/12/29 requesting clarification. Will send shape within a few days. 
From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Monday, January 05, 2015 10:45 PM
To: Susan Foster
Subject: Re: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

No worries. I'll update my shapes and get a .shp file to you within the next day or two.

Cheers,
Amanda

**Comment by SRF-NMP** [comment]
Consultant reclassified several BMP areas as FC if they could not be reshaped, but did not maintain clearances with remainder of sites that could be reshaped to accommodate tree site. Replied to consultant with direction to maintain clearance and reshape:

From: Susan Foster 
Sent: Tuesday, January 13, 2015 10:07 AM
To: 'Baker, Amanda N.'
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Amanda, 

Thank you – I see that you have changed several sites to FC that cannot be reshaped. For the remainder, could the reshaped sites maintain the minimum 20’ clearance between the reshaped site and the footprint (highlighted below)? 

Thanks!

Susie

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Monday, January 12, 2015 2:27 PM
To: Susan Foster
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Susan,

I have uploaded the revised footprints for the 11 facilities in the ISSUES_BA007 file. Here is a link: 2015-01-12-BA Co Gr1-MTI_Tree Conflict_RESPONSE_BA_007

Please feel free to call or email if you need anything else.

Cheers,
Amanda

**Comment by SRF-NMP** [comment]
Consultant has reshaped SW sites to maintain clearance, and sites look good in GIS. 

Kerry, here is the PW link to the folder with reshaped sites/status changes:
pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr1-MTI\08-Submissions\2015-01-12-BA Co Gr1-MTI_Tree Conflict_RESPONSE_BA_007\

Emails below:

From: Susan Foster 
Sent: Tuesday, January 13, 2015 11:44 AM
To: 'Baker, Amanda N.'
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Thanks for reshaping, Amanda! They look good. The main database will be updated. If you have any more questions, please let me know. I understand the tree data can be complicated!

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Tuesday, January 13, 2015 10:56 AM
To: Susan Foster
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Susie,

The revised file is on PW.

Cheers,
Amanda

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Tuesday, January 13, 2015 10:22 AM
To: Susan Foster
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Tuesday, January 13, 2015 10:22 AM
To: Susan Foster
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Susie,

Thank you for the quick explanation! This makes more sense. I’ll revise the file and replace with the one previously uploaded to PW shortly.

Cheers,
Amanda

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Tuesday, January 13, 2015 10:19 AM
To: Baker, Amanda N.
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Amanda,

Thanks – yes, we are working to allow both teams to use a site; however, the issue with this group of sites is that these tree sites were already put into tree contracts/are scheduled to be planted, and the footprints unfortunately cannot be altered – therefore, the only option is to reshape the SWM. This is the “LUCHANGE” layer in which these sites fall (I have highlighted in green the definitions of the feature classes below). There are other sites that are in the group called “TREE_SITE_SELECTION,” and the tree sites that fall in there can be reshaped if they coincide with SWM sites. In those cases, I am having the tree team reshape instead of SWM, and will be sent as a different group (“Issue”). 

I know this is a lot of info! Thanks! Please let me know if you have questions!

Susie

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Tuesday, January 13, 2015 10:11 AM
To: Susan Foster
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Susie,

No problem, I’ll have the shapes updated shortly. My only concern is that several potential sites will have to be moved to future consideration. Is there a process for the SWM and tree folks to work together to make both SWM and tree planting feasible? It seems like some of these sites both options could be feasible with a little coordination.

Cheers,
Amanda

From: Susan Foster 
Sent: Tuesday, January 13, 2015 11:44 AM
To: 'Baker, Amanda N.'
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Thanks for reshaping, Amanda! They look good. The main database will be updated. If you have any more questions, please let me know. I understand the tree data can be complicated!

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Tuesday, January 13, 2015 10:56 AM
To: Susan Foster
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Susie,

The revised file is on PW.

Cheers,
Amanda

From: Susan Foster [mailto:SFoster@nmpengineering.com] 
Sent: Tuesday, January 13, 2015 10:19 AM
To: Baker, Amanda N.
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Amanda,

Thanks – yes, we are working to allow both teams to use a site; however, the issue with this group of sites is that these tree sites were already put into tree contracts/are scheduled to be planted, and the footprints unfortunately cannot be altered – therefore, the only option is to reshape the SWM. This is the “LUCHANGE” layer in which these sites fall (I have highlighted in green the definitions of the feature classes below). There are other sites that are in the group called “TREE_SITE_SELECTION,” and the tree sites that fall in there can be reshaped if they coincide with SWM sites. In those cases, I am having the tree team reshape instead of SWM, and will be sent as a different group (“Issue”). 

I know this is a lot of info! Thanks! Please let me know if you have questions!

Susie

From: Baker, Amanda N. [mailto:ANBaker@mccormicktaylor.com] 
Sent: Tuesday, January 13, 2015 10:11 AM
To: Susan Foster
Subject: RE: Baltimore County Gr1-MTI Potential BMP Conflicts with Tree Planting Areas: Issue_BA_007

Susie,

No problem, I’ll have the shapes updated shortly. My only concern is that several potential sites will have to be moved to future consideration. Is there a process for the SWM and tree folks to work together to make both SWM and tree planting feasible? It seems like some of these sites both options could be feasible with a little coordination.

Cheers,
Amanda

**Comment by kerrymcmahon** [comment]
I have updated the data accordingly and this issue is now closed.
